### ISSUE TITLE
Fedora 41 rpm

### ISSUE THREAD

**Issue by idiot-shinuki** [adoptium/installer#1046]
Fedora 41 just released, and i have the following in `/etc/yum.repos.d/adoptium.repo`:
```
[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/fedora/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
```
Now that I've upgraded from Fedora 40 to 41, the following output shows in my terminal when I run `dnf check-upgrade`:
Updating and loading repositories:
```
 Adoptium                                                                                                                                             100% |   1.3 KiB/s | 320.0   B |  00m00s
>>> Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/41/x86_64/repodata/repomd.xml (IP: 2606:4700::6812:1442) - https://packages.adoptium.net/artifactory/rpm/fedora/
>>> Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/41/x86_64/repodata/repomd.xml (IP: 2606:4700::6812:1442) - https://packages.adoptium.net/artifactory/rpm/fedora/
>>> Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/41/x86_64/repodata/repomd.xml (IP: 2606:4700::6812:1442) - https://packages.adoptium.net/artifactory/rpm/fedora/
>>> Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/41/x86_64/repodata/repomd.xml (IP: 2606:4700::6812:1442) - https://packages.adoptium.net/artifactory/rpm/fedora/
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
Is there any current workaround or ETA for when Fedora 41 packages will be built and released?

**Comment by sxa** [comment]
Discussed at the PMC meeting - Scott will perform this addition.

**Comment by judovana** [comment]
Hello! When in this, can `rawhide` be added too? And `f42` ? With temurins as official jdk provider, the symlinks should be there before, rather then after the branching/release. wddyt?

**Comment by sxa** [comment]
> Hello! When in this, can `rawhide` be added too? And `f42` ? With temurins as official jdk provider, the symlinks should be there before, rather then after the branching/release. wddyt?

I'd be ok with that :-)

**Comment by judovana** [comment]
I thought I already reported it, as I recall discussion about the symlinks. But it seems issue was not filled => https://github.com/adoptium/installer/issues/1053

**Comment by sxa** [comment]
Yeah we've definitely had the discussion more than once. The preferred option is not to have the version in there (https://github.com/adoptium/installer/issues/501) and the symlink thing has been investigated but not implemented (there are some non-trivial quirks with the JFrog upload process there that haven't been worked on more then the initial investigation).

**Comment by steelhead31** [comment]
I'll add 41 & 42, having pulled fedora:rawhide, it actually returns its version number of 42 ( currently.. ) rather than rawhide.

**Comment by steelhead31** [comment]
JDK & JRE 8.0.432 are now available in the artifactory packages repository

**Comment by steelhead31** [comment]
JDK & JRE 11.0.25 are now available in the artifactory packages repository

**Comment by judovana** [comment]
rawhide please,  rawhide.... rawhide to :)

**Comment by steelhead31** [comment]
> rawhide please, rawhide.... rawhide too :)

@judovana Coming very soon :)

**Comment by judovana** [comment]
ty! Highly appreciated! (I had jsut recalled where it was first hit: https://discussion.fedoraproject.org/t/f42-change-proposal-third-party-legacy-jdks-system-wide/132049/27)

**Comment by steelhead31** [comment]
All Fedora 41, 42 & Rawhide packages have been updated on packages.adoptium.net for the most recent release cycle ( October CPU )

JDK8.0.432

JDK11.0.25

JDK17.0.13

JDK21.0.5

JDK23.0.1
