### ISSUE TITLE
keep repository simlinks ahead of fedora schedule

### ISSUE THREAD

**Issue by judovana** [adoptium/installer#1053]
With https://fedoraproject.org/wiki/Changes/ThirdPartyLegacyJdks finished, it would be nice if  symlinks in rpm repository would appear before release of fedora, and even better, before branching of fedora (3months before release, in half of the cycle)

That expects to add `f41` (https://github.com/adoptium/installer/issues/1046) and `rawhide` now. And `f42` in aprox a month. Not sure how to ensure timeliness for future. Maybe the whole 1-99 can be generated  for now, and only trimmed once distribution specific issue rise?

**Comment by sxa** [comment]
Noting that this would also be a valid requirement for Ubuntu which is on a simialr six-monthly cadence

**Comment by sxa** [comment]
This now works:
```
podman run -it fedora:rawhide
dnf install -y adoptium-temurin-java-repository
dnf config-manager setopt adoptium-temurin-java-repository.enabled=1
dnf search temurin
dnf install -y temurin-8-jdk
```
and (at the time of writing) you end up with:
```
[root@61a1d034bdeb /]# java -version
openjdk version "1.8.0_432"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_432-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.432-b06, mixed mode)
[root@61a1d034bdeb /]# 
```

**Comment by judovana** [comment]
Yup. Noted. Thanx!  There may be an reason to reopen the bug - how to keep this permanent, and do not forget add eg  f49?

**Comment by sxa** [comment]
I think keeping on top of new distributions is a generic thing at the project so we just need to plan in a review every six months. We're in a position where we're new ones for testing more frequently, so I'd like to try and do updates to the distributions for both testing and the installers as one action item (until we put something in place to get us version-neutral in the repo files)

**Comment by steelhead31** [comment]
All Fedora 41, 42 & Rawhide packages have been updated on packages.adoptium.net for the most recent release cycle ( October CPU )

JDK8.0.432

JDK11.0.25

JDK17.0.13

JDK21.0.5

JDK23.0.1

**Comment by judovana** [comment]
> This now works:
> 
> ```
> podman run -it fedora:rawhide
> dnf install -y adoptium-temurin-java-repository
> dnf config-manager setopt adoptium-temurin-java-repository.enabled=1
> dnf search temurin
> dnf install -y temurin-8-jdk
> ```
> 
> and (at the time of writing) you end up with:
> 
> ```
> [root@61a1d034bdeb /]# java -version
> openjdk version "1.8.0_432"
> OpenJDK Runtime Environment (Temurin)(build 1.8.0_432-b06)
> OpenJDK 64-Bit Server VM (Temurin)(build 25.432-b06, mixed mode)
> [root@61a1d034bdeb /]# 
> ```

Just for record, it should work already also on rhel8+9:
```
[tester@localhost ~]$ sudo dnf --enablerepo  epel install -y adoptium-temurin-java-repository
[tester@localhost ~]$ sudo dnf --enablerepo adoptium-temurin-java-repository search temurin
[tester@localhost ~]$ sudo dnf --enablerepo adoptium-temurin-java-repository  install -y temurin-8-jdk
[tester@localhost ~]$ java -version
openjdk version "1.8.0_432"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_432-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.432-b06, mixed mode)
[tester@localhost ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.4 (Plow)
```

Only the `dnf config-manager setopt adoptium-temurin-java-repository.enabled=1`  did not worked for me.

**Comment by sxa** [comment]
> Just for record, it should work already also on rhel8+9:

That's cool! :-) Thanks for sharing.
