### ISSUE TITLE
Fedora 41 x86_64 Adoptium repo error

### ISSUE THREAD

**Issue by idiot-shinuki** [adoptium/installer#1065]
The repo data seems to be incorrect. Most likely fix would be to run `createrepo_c` at https://packages.adoptium.net/ui/native/rpm/fedora/41/x86_64/
![image](https://github.com/user-attachments/assets/a3d490ba-7306-46a1-8f75-0c06e9f5614c)
I'm unsure if any other arches/fedora releases/distros are functioning properly, I'm only able to test for my own system.

**Comment by sfc-gh-abalik** [comment]
I'm seeing something similar on rocky 9 pulling from the rhel 9 repo:

```
[root@56d61bb42efc /]# dnf install temurin-17-jdk
adoptium                                                                                                                         17 kB/s | 3.4 kB     00:00
Error: Failed to download metadata for repo 'adoptium': repomd.xml parser error: Parse error at line: 1 (Specification mandates value for attribute en
)
```

This worked earlier today, but stopped working sometime in the afternoon PST.

**Comment by judovana** [comment]
Just for record on f40, right now, I was able to install all temurin jdks from Eclipse temurin repository. I had cleared caches before trying. Similarly, in fresh 41 container, I was able to install `adoptium-temurin-java-repository` and then any temurin jdk/jre.  So maybe temporary outage, or already solved?

```
    1  dnf install *temurin*
    4  dnf install vim
    5  vim /etc/yum.repos.d/adoptium-temurin-java-repository.repo 
    7  dnf install temurin-17-jdk
    8  java -version
    9  history 
[root@b9b7cc58a4b0 /]# java -version
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)
```

**Comment by sfc-gh-abalik** [comment]
I just tried again on rocky 9 and it's working, so this seems to be fixed now.

**Comment by idiot-shinuki** [comment]
> I just tried again on rocky 9 and it's working, so this seems to be fixed now.

Can confirm that there is no longer an issue on my end. I don't know what it was but it looks like it fixed itself. What makes it weird is that I looked at that Artifactory link and nothing's changed about any of those files since the 14th of November this year. Dnf was complaining about the `repomd.xml` file for some reason, and somehow, without anything seemingly changing, the issue somehow resolved itself.

**Comment by karianna** [comment]
We applied a fix behind the scenes, thanks for the patience folks!
