### ISSUE TITLE
Update README.md to describe how we put together deb and rpms

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#117]
The main READMe file does not link to the linux subdir readme file to describe how those installers are built.

**Comment by 2001asjad** [comment]
Hi @karianna . I would like to give this issue a try .

**Comment by karianna** [comment]
@2001asjad Great! If you dig into the code of this repository you should see references to both of those installers.  See if that makes sense to you and if not you can ask @aahlenst here or on Slack for some guidance.

**Comment by 2001asjad** [comment]
@karianna Please review my PR and suggest changes if required. Thank You.

**Comment by karianna** [comment]
> @karianna Please review my PR and suggest changes if required. Thank You.

Can you open the PR on this repository?  I think you opened one on your own repo by accident.

**Comment by 2001asjad** [comment]
@karianna Please take a look. One of my tests is failing

**Comment by tellison** [comment]
Although this is tagged as a good first issue, it doesn't seem to have a useful description of what is wrong/required.  I'll let @karianna expand on the expectations.

The PR seems to be describing how to use the install packages?

The way the Linux packages are built is addressed in the [linux subdir readme](https://github.com/adoptium/installer/tree/master/linux#readme).

**Comment by karianna** [comment]
Tim is indeed correct.  You can change your PR to link to the [linux subdir readme](https://github.com/adoptium/installer/tree/master/linux#readme) file
