### ISSUE TITLE
Do not require users to explicitly accept the terms of the GPLv2+CE

### ISSUE THREAD

**Issue by tellison** [adoptium/installer#162]
As noted by by [@FreyjaDomville](https://twitter.com/FreyjaDomville/status/1175126558681501696) via Twitter.

While not prohibited, end users should not be _required_ to click through accept the GPLv2 terms, see the [GNU FAQ site](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#ClickThrough).

As a convenience, please remove explicit license terms acceptance from our installers.

**Comment by douph1** [comment]
Fixed in #307
