### ISSUE TITLE
For .MSI: use $JAVA_HOME% in windows path

### ISSUE THREAD

**Issue by hegGK** [adoptium/installer#195]
Currently the msi installer sets the JAVA_HOME variable to the install directory and the full path to the bin directory in the windows path environment variable. 

If it would use %JAVA_HOME%\bin in the path, it would be possible to switch Java versions just by switching the JAVA_HOME variable.

**Comment by douph1** [comment]
I don't know if it can work and work without drawback
>https://superuser.com/questions/27826/why-cant-windows-handle-an-environment-variable-in-path

 but

>FeatureJavaHome | Update the JAVA_HOME environment variable
is an option not set by default

and changing PATH to use JAVA_HOME will add some complexity ..

I even don't know if it possible as FeatureJavaHome is a feature Level=2 set after FeatureEnvironment Level=1

In case of multiple msi install ( 8 + 11 ) , MSI actually remove (on uninstall)  the corresponding part from the PATH with the real bin path corresponding to 8 or 11.
If all MSI use the same bin path %JAVA_HOME%\bin .. i assume the installer will probably remove it on uninstall and break the two java 8 and 11 .. (I haven't tested it though)

Seems difficult and risky to me

**Comment by douph1** [comment]
This issue has not get any comment from the author or likes from the community since more than one year.
I consider to close it as "won't fix" due to the lack of global interest.

**Comment by tellison** [comment]
@douph1 just close it as such, and the reporter can reopen if required.
