### ISSUE TITLE
Would you plan to add Alpine repo ?

### ISSUE THREAD

**Issue by abcfy2** [adoptium/installer#220]
Features that impact the whole project (e.g. Adding a new OpenJDK distribution)are made over at the [TSC](https://github.com/AdoptOpenJDK/TSC/).

Would you plan to add Alpine repo ?

I find the zulu jdk already support Alpine repo: https://docs.azul.com/zulu/zuludocs/ZuluUserGuide/PrepareZuluPlatform/AttachAPKRepositoryAlpineLinux.htm

I think it's cool that AdoptOpenJDK also support Alpine repo.

**Comment by aahlenst** [comment]
I have plans, actually. But there was no demand so far and, personally, I do not see much value in it as long as there is no AdoptOpenJDK build that works with musl libc. The Docker images we produce require glibc. Azul has musl builds, most likely as a result of [Portola](https://openjdk.java.net/projects/portola/). musl support should become an official part of OpenJDK with [JEP 386](https://openjdk.java.net/jeps/386). It hasn't landed yet, maybe in 16? I expect us to provide an APK repository by then.

**Comment by stevenschlansker** [comment]
Alpine port is now considered production ready as of 16 GA: https://mail.openjdk.java.net/pipermail/portola-dev/2021-May/000517.html
AdoptOpenJDK provided a 16 Alpine Docker image: https://hub.docker.com/r/adoptopenjdk/openjdk16 but it seems slightly out of date (16.0.1 vs 16.0.2 is latest now)
Part of the lack of demand I think is the difficulty of finding a vendor providing out of the box binaries - most people don't want to compile their own source. It would be cool to have an Alpine package with openjdk available - we'd certainly try it.

**Comment by gdams** [comment]
I've been experimenting with pushing some apk files up if people want to have a go with them and provide some feedback?

add the public key:

```bash
wget -O /etc/apk/keys/adoptium.rsa.pub https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk
```

add the repo:

```bash
echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >> /etc/apk/repositories
```

install JDK (replace with 17/11/8 etc)

```bash
apk update # if needed
apk add temurin-<version>-jdk
```

**Comment by lfvjimisola** [comment]
@gdams It no longer works for us with the steps below. Has there been any chances now that your contribution has closed the issue?

```
RUN curl https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk -o /etc/apk/keys/adoptium.rsa.pub \ 
    echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >> /etc/apk/repositories \
    apk update && apk add temurin-17-jdk
```

**Comment by gdams** [comment]
@lfvjimisola what doesn't work? Are you able to send me any logs/error messages?

**Comment by lfvjimisola** [comment]
> @lfvjimisola what doesn't work? Are you able to send me any logs/error messages?

It works now of course (rubber ducking and Murphy at their best). Suspecting network/forward proxy issues at our end. Sorry for disturbing you.

**Comment by lfvjimisola** [comment]
1. Will the package repo `https://packages.adoptium.net/ui/native/apk/alpine/main/` contain historical Eclipse Temurin apk versions? And if so, for as long as for other platforms (including tar.gz)?

2. Are there any plans of providing the JRE as apk packages as well? Would be a huge improvement when using Eclipse Temurin in alpine containers.

**Comment by lfvjimisola** [comment]
Will the adoptium apk repo main historic version just like for other builds/packages?

**Comment by lfvjimisola** [comment]
We use [renovate for version monitoring](https://docs.renovatebot.com/modules/datasource/#repology-datasource) and it works for standard apk packages. However, it does not work since Eclipse Temurin packages in its [alpine repository](https://repology.org/repositories/statistics) are not available in [Repology](https://repology.org). Is that something that you might consider?

Another option would be to use [GitHub releases API](https://github.com/adoptium/temurin17-binaries) but those version number to not match APK version number.

**Comment by jimisola** [comment]
@gdams

1. I was able before to browse to https://packages.adoptium.net/artifactory/apk/alpine/main and see all available versions. That is no longer the case as a JFrog login page shows for which I don't have login info. Can I see available apk version on the web somewhere (the version string is bit different than if I go to the regular download site)?  
Currently, it seems as the following versions are available:

```
temurin-17-jdk-17.0.4.1_p1-r0
temurin-17-jdk-17.0.5_p8-r0
temurin-17-17.0.4.1_p1-r0
temurin-17-17.0.5_p8-r0
temurin-17-src-17.0.4.1_p1-r0
temurin-17-src-17.0.5_p8-r0
```

2. Is `temurin-17-17.0.5_p8-r0` JRE only? Is it possible to install just the JRE? `apk add temurin-17` or `temurin-17-17.0.5_p8-r0```seems to install the JDK.

3. Are you planning to change to apk install instead of tarball in the [official images](https://github.com/adoptium/containers/issues)? Would be nice to know that the apk are used officially as well in case of bugs etc.
