### ISSUE TITLE
create_installer_windows always download icedtea-web but required only for OpenJDK 8

### ISSUE THREAD

**Issue by douph1** [adoptium/installer#278]
Just need some version testing before download itw

**Comment by junyuan-z** [comment]
@douph1 we have a feature request to make the icedtea-web optional for OpenJDK 8 and I will work on this. So do you want to assign this to me?

**Comment by douph1** [comment]
This is not the direction of this issue. Icedtea-web is not optional for OpenJDK8 during build phase. It is required to build OpenJDK8 and optional at install time.
The goal of this issue is for the installer job to not download/uncompress icedtea-web when building MSI for jdk 11 and more because we don't package icedtea-web in other version than JDK8.

Your feature request is to build msi JDK8 without even propose Icedtea-Web ?

**Comment by junyuan-z** [comment]
Ah, I see. We need to create an MSI package without `IcedTea-Web` and `JavaSoft (Oracle) registry keys`. I am not sure what's the best way to implement this and whether we can upstream those changes.

**Comment by douph1** [comment]
itw is already not download with github action and now is not download anymore on https://ci.adoptopenjdk.net/

I have juste enclosed the download with a "if" on the job ( no code on repo changed )
>if "%PRODUCT_MAJOR_VERSION%" == "8" (
