### ISSUE TITLE
Incorporate adoptium-packages-linux into the installer story at adoptium

### ISSUE THREAD

**Issue by smlambert** [adoptium/installer#311]
This issue encompasses the incorporation of the contents of https://github.com/aahlenst/adoptium-packages-linux into the adoptium installer approach.  NOTE:  some of the discussion on this topic has already taken place in https://github.com/adoptium/installer/issues/205.

It includes:
- moving the contents of adoptium-packages-linux to this repo (original plan was to leave it as a standalone repo, in April 21st PMC meeting project leads indicated preference to blend it into this existing repository)
- creating Jenkinsfile / groovy script for creating the adoptium-packages-linux packages and triggering the tests that are also contained in adoptium-packages-linux
  - pipeline for creating these packages can be triggered both via a release pipeline (in ci-jenkins-pipelines repo) and standalone
  - pipeline should be able to take artifacts from upstream or from customized location
  - pipeline should have option to publish or not
  - pipeline should not publish if tests fail
- We will continue to use the current approach for creating linux installers as this work is being done and will not make a full switch over until we arrive at an equivalent or better installer production story.

For the publishing piece, we (PMC and WG) still need to determine which hosting options are available to us and make a decision as there will be a cost involved that will need to be voted on / accounted for in budget.  Andreas and George had been in contact with several hosting services.  Andreas has forwarded that information to Shelley and Stewart and we are re-engaging with those contacts.

**Comment by smlambert** [comment]
FYI @jerboaa

**Comment by jerboaa** [comment]
@smlambert thanks for the heads-up.

**Comment by jerboaa** [comment]
@AdamBrousseau @sophia-guo @smlambert Let's just use this issue for the integration of the rewrite work.

**Comment by AdamBrousseau** [comment]
Seems this and https://github.com/adoptium/ci-jenkins-pipelines/issues/84 are dup. Should one be closed?

**Comment by jerboaa** [comment]
@smlambert @AdamBrousseau I thought part of this issue was to merge https://github.com/aahlenst/adoptium-packages-linux into https://github.com/adoptium/installer repo. Has this happened yet? That's what I'm waiting for, fwiw :) Re-opening for now.

**Comment by jerboaa** [comment]
Initial merge of new linux installer work has been done in #312

**Comment by karianna** [comment]
I'm going to close this issue and open a new one to track the work needed to be done to bring this to Production
