### ISSUE TITLE
Windows installer should always grab latest IcedTea-Web release

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/installer#317]
At the moment the ITW version is hardcoded in the installer job. I have my own fork of the job so my problem is I have to subscribe to the ITW GitHub repo in order to get notified about new builds (releases). I also don't have permissions to view the job at Adopt so that doesn't help either. It would be handy if the job could always fetch the latest release.

https://docs.github.com/en/rest/reference/repos#get-the-latest-release
https://api.github.com/repos/AdoptOpenJDK/IcedTea-Web/releases/latest

**Comment by douph1** [comment]
with reverse quote " vs '
>curl -s https://api.github.com/repos/AdoptOpenJDK/IcedTea-Web/releases/latest | jq -r '.assets[] | select(.name | endswith("win.bin.zip")) | .browser_download_url'
https://github.com/AdoptOpenJDK/IcedTea-Web/releases/download/icedtea-web-1.8.7/icedtea-web-1.8.7.win.bin.zip

added into Jenkins job as commented code.

We actually can't include ITW in Temurin build. If/When ITW will be included it will take the latest

**Comment by mibyge** [comment]
@douph1 Can you please elaborate on why IcedTea-Web is not included in the Temurin release since they were included in the AdoptOpenJDK JRE releases?

And are you working on getting it included again, or should we instead focus on installing it separately if we need it?

Thanks.

**Comment by karianna** [comment]
You should focus on installing it separately. We weren't able to bundle it at Eclipse due to a myriad of legal/compliance/security reasons.
