### ISSUE TITLE
Problem uninstalling AOJDK 11.0.7_10 OpenJ0.20.0 (x64) LTS in Windows 10 2H2 x64

### ISSUE THREAD

**Issue by succeedmr123** [adoptium/installer#318]
This is a copy/move from temurin-build Issue #2572 at github https://github.com/adoptium/temurin-build/issues/2572

(as the topic also concerns the installer, and it could be useful to all to open the issue here under /installer  for everyones benefit, as kindly suggested by @karianna )

What are you trying to do?

-to uninstall OLD LTS (to upgrade to a current JDK 11 LTS (11.0.10_9_openj9-0.24.0.msi)) - currently the installer and the associated uninstaller is stuck, impossible to uninstall it

Expected behaviour:

Old 11 LTS 11.0.7_10 to be uninstalled smoothly (and replaced with the new one)

Observed behaviour:

The old AOJDK can not be uninstalled from windows system by its uninstaller, even if it is exactly the same name dot subvairiant etc.

When trying to circumvent the problem by installing new LTS supposedly to uninstall or rewrite registry entries pointing to the correct LTS - it fails the same by invoking the same old failing uninstaller script.

It asks for .msi name AOJDK EOJ9 11.0.7_10 (x64) , and when matched - just refuses to proceed and continues to insist that it is not the right one, although the name and variant is the exact subvariant dots and an exact match of a filename (downloaded .msi of the 11.0.7.10 build from github while trying to correct the situation)

Any other comments:

By the way of trying to resolve this, under releases history I noticed some sub-variant versions of LTS 11.0.10_9 / openj9.0.24.0 installer on github - it would be good to get everything coherent  in th final outcome of eradicating .msi uninstall problem for good.

Useful observation: A solid manual removal instructions is missing - it was not possible to find it only by search engine query.

Thank you in advance for considering this critical uninstaller bug

**Comment by douph1** [comment]
Please give us some log files from the msi

>msiexec /x "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"

Then try to reboot and uninstall.

**Comment by succeedmr123** [comment]
@douph1 

Thank you for the swift reply; as I am in daily workplace, will try to provide log answer ASAP in the work break.

Thank you for the log cmd line as the next step, have a great day!

**Comment by douph1** [comment]
Closed as no new input since long time
