### ISSUE TITLE
Installer adds bin folder to start of system path

### ISSUE THREAD

**Issue by mconnew** [adoptium/installer#319]
## Summary
While installing AdoptOpenJDK-11.0.11+9 on Windows, the installer gave the option to add the bin folder to the system path. When it did this, the open jdk bin folder was prepended to the system path instead of postpended. This makes the OpenJDK folder the very first folder searched on the search path. There is at least one name clash between a Windows system exe and an AdoptOpenJDK binary. There is a binary called klist.exe that exists in c:\windows\system32 as well as in C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin. This resulted in my believing I had 0 Kerberos tickets issued to me as the the AdoptOpenJDK kerberos stack isn't aware of the system Kerberos stack (which in itself seems like the wrong behavior, but that's another issue).

## Steps to reproduce
1. Install AdoptOpenJDK-11.0.11+9 on a domain joined Windows PC.
2. Open a command prompt and execute "klist"

## Expected results
The AdoptOpenJDK bin folder to be added to the end of the system PATH during install.
To see a list of my issued Kerberos tokens from my domain controller.

## Actual results
The AdoptOpenJDK bin folder placed at the start of the system path before c:\windows\system32
A one line error message stating:
```
Credentials cache C:\Users\USERNAME\krb5cc_USERNAME not found.
```

## Triaging info

Java version:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

What is your operating system and platform?
Microsoft Windows [Version 10.0.19043.985]

How did you install Java?
From MSI downloaded from GitHub releases

Did it work before?
Never installed AdoptOpenJDK before

Did you test with other Java versions?
No. This is the most recent LTS build and the installer should do the correct thing regardless of what the latest version (OpenJDK 16 in this case) does so didn't see a need to check other behavior.

**Comment by douph1** [comment]
Thanks for you report.
Did it break a tool ?
Or just you relying on the PATH ?

>When it did this, the open jdk bin folder was prepended to the system path instead of postpended. This makes the OpenJDK folder the very first folder searched on the search path. 

This is a intended choice so each newer install become the new default one.
Like overwrite JAVA_HOME with the new

All binary can be present multiples times in the PATH.
It will be the same for different vendor build of OpenJDK who all add their bin/ to the PATH.
If Adoptium will have been postponed to the path, depsite it will be the latest installed, it will not be taken into account by relaying in the PATH.. so not usable by the PATH at all.
So postponed is not so well
I think added to the PATH must always be prepended so newer tools take precedence on older.

>Did you test with other Java versions?

We can add another question :
>Did you test with other Java vendor ?

We all try to align this kind of choice so switching from one vendor to another will by flawless

**Comment by karianna** [comment]
@mconnew ^^

**Comment by mconnew** [comment]
> Did it break a tool ?
Or just you relying on the PATH ?

It caused me problems diagnosing an authentication problem completely unrelated to Java at the command line, so wasn't a tool problem. I could certainly see this breaking some scripts which depend on the klist command, but that wasn't my case.

I understand the need to make the latest java exe being picked up, but you shouldn't be causing your own tools to be picked up before OS binaries of the same name. You could parse each PATH item starting at the beginning and find the first folder which already contains java.exe and add your path before that one, although that can be non-deterministic because you can add relative paths to the PATH. If someone is doing something weird with relative paths for java, then I would say they are capable enough to manage that themselves. Relative paths in the PATH is a security problem so not finding the right version of java is probably the least of their worries.  

Another option is to detect system paths at the start of the PATH and don't preempt them.

**Comment by douph1** [comment]
>it caused me problems diagnosing an authentication problem completely unrelated to Java at the command line, so wasn't a tool problem.

Good :)

>I could certainly see this breaking some scripts which depend on the klist command

sure

>, but that wasn't my case.

cool :)

>I understand the need to make the latest java exe being picked up, 

:+1: 


>but you shouldn't be causing your own tools to be picked up before OS binaries of the same name.

I'm agree this is not the best part of this choice


> You could parse each PATH item starting at the beginning and find the first folder which already contains java.exe and add your path before that one,

Even if we wanted to do it, I don't know how.
Actually we only use WIX feature:

https://github.com/adoptium/installer/blob/master/wix/Main.wxs.template#L102
or
https://github.com/adoptium/installer/blob/master/wix/Main.wxs.template#L107

>Another option is to detect system paths at the start of the PATH and don't preempt them.

I'm not sure to understand what you mean, but as before .. we are not able to do it with the base Wix feature:
https://wixtoolset.org/documentation/manual/v3/xsd/wix/environment.html
