### ISSUE TITLE
INSTALLLEVEL=3 inclusion of IcedTea-Web fails to set JNLP MIME type in registry

### ISSUE THREAD

**Issue by middletonk** [adoptium/installer#322]
Hi folks, apologies, AdoptOpenJDK seems to replicate a known issue that was resolved in the IcedTea-Web standalone installer, [issue # 371](https://github.com/AdoptOpenJDK/IcedTea-Web/issues/371). This issue is failure to create registry key HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/x-java-jnlp-file, which in turn means that JNLP web content is downloaded without OS/browser capacity to translate to a known file extension. This then in turn prevents group policies for Edge Chromium to auto-open by filetype on trusted domains as there is no file extension.

Happy to elaborate on this request as needed. Thank you for the consideration!

**Comment by douph1** [comment]
issue placed in wait state as we don't include ITW in new Temurin build for now

**Comment by psoujany** [comment]
@douph1 We see similar issue with Semeru JDK8 build which has ITW shipped. Could you please check on this. Thank you

**Comment by middletonk** [comment]
Since this was bumped, I suppose I'll add a question - was ITW ever re-added to new Adoptium Temurin builds for JRE 8? Thank you!

**Comment by karianna** [comment]
> Since this was bumped, I suppose I'll add a question - was ITW ever re-added to new Adoptium Temurin builds for JRE 8? Thank you!

In short no - but you can follow the blog post on how to add it from the blog.adopopenjdk.net site.

**Comment by psoujany** [comment]
@douph1 Semeru JDK8 has ITW with it and we see issue with JNLP registry keys, could you please check this.

**Comment by psoujany** [comment]
Raised a PR with changes
https://github.com/adoptium/installer/pull/547
