### ISSUE TITLE
Eclipse signing is failing silently

### ISSUE THREAD

**Issue by douph1** [adoptium/installer#323]
then the MSI is published : sample :

https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2021-07-26-19-42-beta/OpenJDK8U-jdk_x64_windows_hotspot_2021-07-26-19-42.msi

MSI content : 
>HTTP Error 500
>Problem accessing '/authenticode/sign'
>Reason: Server Error

**Comment by karianna** [comment]
The root cause has been fixed but keeping this open until we have a more robust installer check for future as per the PR incoming

**Comment by douph1** [comment]
>The root cause has been fixed
until the sign API will be down ?

You want to keep the issue open without merging the kinked PR ? Or can I merge the PR now .. or after the release ?
