### ISSUE TITLE
select which libffi (6|7) to install for s390 support.

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#333]
Additional entry required: `libatomic1 [armhf]`

Then there's a more complex one: OpenJDK's s390x port requires libffi6 because Zero needs libffi. Ubuntu 18.04 and Debian Buster are the last ones that ship libffi6. The upcoming Debian Bullseye, Ubuntu 20.04 and newer only include libffi7. So adding `libffi6 [s390x]` would be required for Ubuntu 18.04 and Debian Buster and earlier but that makes the package not installable on more recent Debian/Ubuntu versions. The only way out of this mess would be to split the packages and see if OpenJDK 8 can work with libffi7. But considering that s390x only supports Zero, I'd just drop support for s390x.

For future reference, how to compile this list: Download the JDK of each platform, run a script like https://github.com/adoptium/installer/blob/master/linux/required_libs.sh (works on any architecture, so you can even do this on a Mac) and resolve the name of the libraries with the function "Search the contents of packages" on https://packages.debian.org and https://packages.ubuntu.com.

_Originally posted by @aahlenst in https://github.com/adoptium/installer/pull/332#discussion_r684623237_

**Comment by gdams** [comment]
Closing - we don't ship a zero build of s390x and libatomic1 has been addressed via https://github.com/adoptium/installer/pull/414
