### ISSUE TITLE
Debian Repositories Broken Again?

### ISSUE THREAD

**Issue by janagyjr** [adoptium/installer#340]
I was searching around for already answered issues and found [this one](https://github.com/adoptium/infrastructure/issues/1399) but it's been closed. I'm having this same issue on a fresh VM install of Debian Bullseye. I'll probably use the workaround indicated in the referenced issue but thought y'all should know it's acting up again.

**Comment by karianna** [comment]
We'll be moving package repos soon - https://github.com/adoptium/installer/issues/330
