### ISSUE TITLE
Please upgrade Java 8 Debian package to 8u302

### ISSUE THREAD

**Issue by chriskilding** [adoptium/installer#342]
I believe upstream OpenJDK has now released 8u302. Please could you upgrade the AdoptOpenJDK Debian / RPM packages to 8u302?

(I'm assuming Adopt hasn't done this yet since the highest version here is 8u292: https://adoptopenjdk.jfrog.io/ui/native/deb/pool/main/a/adoptopenjdk-8-hotspot)

**Comment by karianna** [comment]
See https://github.com/adoptium/installer/issues/330

**Comment by chriskilding** [comment]
Ok - so we need to wait for the shift to Adoptium to get 8u302?

Also will we see the new Adoptium deb packages in the same adoptopenjdk.jfrog.io repo, or will they be hosted somewhere new?

**Comment by karianna** [comment]
> Ok - so we need to wait for the shift to Adoptium to get 8u302?
> 
> Also will we see the new Adoptium deb packages in the same adoptopenjdk.jfrog.io repo, or will they be hosted somewhere new?

Yes on the first point and finally we have https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/ on the 2nd point :-)
