### ISSUE TITLE
JRE with Hotspot 11.0.12+7 x86 msi installer installs 17.0.0.35 version instead of 11.0.12.7

### ISSUE THREAD

**Issue by Kurkinen** [adoptium/installer#348]
**The issue:**
Msi installer of the latest version of JRE with Hotspot 11 x86 installs 17.0.0.35 version of the application. The actual version should be 11.0.12.7. ProductName property of the installer is correct (_Eclipse Temurin JRE with Hotspot 11.0.12+7 (x86)_) but the ProductVersion is 17.0.0.35 and all the files will be installed to C:\Program Files (x86)\Eclipse Foundation\jre-**17.0.0.35-hotspot** folder

**To reproduce:**
- Download the installer: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jre_x86-32_windows_hotspot_11.0.12_7.msi
- Install and check installation location and jre version

**Comment by gdams** [comment]
Thanks for the bug report @Kurkinen. We have re-spun that particular JRE and released it here: https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.12%2B7.1

Please feel free to re-open this issue if you have further problems
