### ISSUE TITLE
Change Installation folder in Windows from "Eclipse Foundation" to "Adoptium" inline with other installers

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#352]
As per PMC's decision quite some time ago.

**Comment by douph1** [comment]
I will take a look. Any deadline ?

**Comment by sxa** [comment]
It's required for this week's release, so realistically we'd want it for tomorrow evening.

**Comment by gdams** [comment]
This was changed to Eclipse Adoptium which I think is good enough for us to close this
