### ISSUE TITLE
Debian package repo

### ISSUE THREAD

**Issue by sideeffect42** [adoptium/installer#364]
With AdoptOpenJDK installing a JDK/JRE was as easy as adding the repository to APT and installing the desired package.

I couldn't find a package repo for Adoptium. Is there or will there be an APT/DEB repository for Adoptium builds?

**Comment by sxa** [comment]
Absolutely! We are actively working on it and the work is covered by https://github.com/adoptium/installer/issues/330 - apologies for the delay in getting this to production.
