### ISSUE TITLE
Publish Linux Temurin packages to apt/yum repositories

### ISSUE THREAD

**Issue by sxa** [adoptium/installer#369]
We have previously look at publishing to a repository hosted at Eclipse Nexus, but the PMC has chosen to continue with publishing at JFrog's Artifactory for the time being. This issue will cover any actions related to publishing the packages to that location once we start producing them.

**Comment by gdams** [comment]
JFrog is now live (adoptium.jfrog.io)

**Comment by sophia-guo** [comment]
Did this mean we can close https://github.com/adoptium/installer/issues/367?

**Comment by smlambert** [comment]
In discussion with @sophia-guo, we are going to pursue using the artifactory Jenkins plugin for upload.  I'll create a standalone job that can push files from a directory and do some trial pushes to adopitum.jfrog.io (checking that we have the correct credentials, etc).  This can then be used as a somewhat manual way to upload files while we work on integrating it into the actual pipelines.  Sophia will make changes to the actual pipeline scripts to be able to integrate this approach, and we will meet somewhere in the middle.

**Comment by sophia-guo** [comment]
Could we first confirm that the artifactory plugin is stalled? https://plugins.jenkins.io/artifactory/. If not could we install it? @sxa

**Comment by smlambert** [comment]
I have just installed [it](https://plugins.jenkins.io/artifactory) @sophia-guo

**Comment by sophia-guo** [comment]
I have tried to manually upload two rpm package to adoptium.jfrog.io to see how jfrog works. Have a few questions. 

1. Current we have only deb and rpm repo. Suppose that the repo or directory will gradually increase to be same as the old adoptOpenJDK  https://adoptopenjdk.jfrog.io/ui/packages? 
2. What does the package under https://adoptium.jfrog.io/ui/repos/tree/General/rpm%2Fcentos%2F7%2Fx86_64%2FPackages mean? RedHat rpm temurin-8-jdk-8.0.312.0.0.7-1.x86_64.rpm
 is generated using fedora:33 https://github.com/adoptium/installer/blob/master/linuxNew/jdk/redhat/src/main/packaging/Dockerfile , is it right to publish to all different os or it can only be published to fedora/33?

**Comment by smlambert** [comment]
Partial answer to question 1) is that we are simplifying what we do and what we produce, so the old structure will not be fully reproduced (not be pushing nightly packages up at all, so no rpm-nightly or deb-nightly for example).

I don't know the answer to question 2, but I am guessing that 
https://adoptium.jfrog.io/ui/repos/tree/General/rpm%2Fcentos%2F7%2Fx86_64%2FPackages
and
https://adoptopenjdk.jfrog.io/ui/repos/tree/General/distribution-repo%2Frpm%2Fcentos%2F7%2Fx86_64%2FPackages
are somewhat similar.

**Comment by jerboaa** [comment]
>     2. What does the package under https://adoptium.jfrog.io/ui/repos/tree/General/rpm%2Fcentos%2F7%2Fx86_64%2FPackages mean? RedHat rpm temurin-8-jdk-8.0.312.0.0.7-1.x86_64.rpm
>        is generated using fedora:33 https://github.com/adoptium/installer/blob/master/linuxNew/jdk/redhat/src/main/packaging/Dockerfile , is it right to publish to all different os or it can only be published to fedora/33?

I'm not sure I understand the question. IIRC, we build on some rpm host (for RPM building), and also run tests on the supported target OS. If the RPM tests pass on the target os it should be fine to publish to the target OSes jfrog repo (like CentOS 7). Note that testing for installability and smoke is key as there are version differences between rpmbuild of say newer Fedora and (older) RHEL/CentOS. FWIW, actual distro packages build on the same OS version than the target repo.

Aside: Fedora 33 is nearing EOL and the docker file should get upgraded to F35 (latest fedora).

**Comment by gdams** [comment]
This can now be closed
