### ISSUE TITLE
Github checks failing for Temurin 8 and 17 redhat

### ISSUE THREAD

**Issue by sxa** [adoptium/installer#378]
Raising as a result of seeing the checks failing on multiple PRs:

> Temurin 8 redhat github check failed but I've seen intermittent failures on those, so I'm going to force a re-run of the checks.

Those failures (Also on 17 redhat) seem to be happening for other PRs so I'm not going to let that block merging of this, but they will need to be addressed - will raise as a separate issue.

_Originally posted by @sxa in https://github.com/adoptium/installer/issues/376#issuecomment-971461741_

**Comment by jerboaa** [comment]
Those are test failures. I believe because of #375

**Comment by sophia-guo** [comment]
Yes, those are test failures, which is the dup of #375. This should be fixed by https://github.com/adoptium/installer/pull/379/commits/4b1f0a26d14af0027d31047b1b257ec2d3b64c60
