### ISSUE TITLE
Suse tests failed on Jenkins jobs

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/installer#385]
Tests have been limited to x86-64, jobs in github action ci passed. Consistently failed in jenkins jobs

```
> Task :jdk:suse:checkJdkSuse
Picked up _JAVA_OPTIONS: -Xmx4g

ZypperOperationsTest > opensuse/leap:15.1 FAILED
    org.opentest4j.AssertionFailedError at ZypperOperationsTest.java:58

ZypperOperationsTest > opensuse/leap:15.2 FAILED
    org.opentest4j.AssertionFailedError at ZypperOperationsTest.java:58

2 tests completed, 2 failed

> Task :jdk:suse:checkJdkSuse FAILED
```
https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/1/console

**Comment by smlambert** [comment]
Will be useful to update that code to print out the non-zero error code, https://github.com/adoptium/installer/blob/master/linuxNew/jdk/suse/src/packageTest/java/packaging/ZypperOperationsTest.java#L58

**Comment by gdams** [comment]
So these tests are failing because Zypper cannot locate the public signing key to verify the GPG signature. I did a quick bit of investigation bit it seems that there is no easy way to skip the verification. As a short term measure, we could import our public key but that wouldn't resolve things for other vendors using our scripts (if any)

**Comment by jerboaa** [comment]
Failure seems to be this:
```
Looking for gpg key ID 65F8F04B in cache /var/cache/zypp/pubkeys.

Repository Plain RPM files cache does not define additional 'gpgkey=' URLs.

Abort, retry, ignore? [a/r/i] (a): a
```

and

```
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
Please see the above error message for a hint.
temurin-17-jdk-17.0.1.0.0.12-1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]
```

**Comment by jerboaa** [comment]
> So these tests are failing because Zypper cannot locate the public signing key to verify the GPG signature. I did a quick bit of investigation bit it seems that there is no easy way to skip the verification.

How about?

```
zypper --no-gpg-checks <cmd>
```

**Comment by gdams** [comment]
Looks like I was trying that flag in the wrong location (after the `install`). That seems to work nicely, I'll raise a PR
