### ISSUE TITLE
Cross-building arm32 rpm packages on x86-64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/installer#390]
Support rpm packages for arm32

**Comment by sophia-guo** [comment]
Trying to enable target arm32on x86-64 and got the error for jdk8. 

```
+ sha256sum -c /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_arm_linux_hotspot_8u312b07.tar.gz.sha256.txt
OpenJDK8U-jdk_arm_linux_hotspot_8u312b07-aarch32-20211101.tar.gz: FAILED open or read
sha256sum: OpenJDK8U-jdk_arm_linux_hotspot_8u312b07-aarch32-20211101.tar.gz: No such file or directory
sha256sum: WARNING: 1 listed file could not be read
```

The arm32 jdk file is  OpenJDK8U-jdk_arm_linux_hotspot_8u312b07-20211101.tar.gz while the sha file refer the name as OpenJDK8U-jdk_arm_linux_hotspot_8u312b07-aarch32-20211101.tar.gz. Looks like the sha file wasn't generated correctly and I can see this only happened to [jdk8u302-b08](https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u302-b08) .

**Comment by sxa** [comment]
OK this sounds like it is another undocumented part of the release process that we need to address. I've raised https://github.com/adoptium/temurin-build/issues/2792 and will get the sha256 file adjusted shortly.

**Comment by sxa** [comment]
Now fixed in the release. Please try again.

**Comment by sophia-guo** [comment]
@sxa Looks like only updating the sha file won't work. The tar.gz unzipped to folder jdk8u312-b07-aarch32-20211101, which is supposed to be `jdk8u312-b07`. Maybe the way the jdk was tarred should be fixed?

**Comment by sxa** [comment]
> The tar.gz unzipped to folder jdk8u312-b07-aarch32-20211101, which is supposed to be jdk8u312-b07

This is consistent with how it was for previous releases and is related to the alternate repository that we build from so I'd be reluctant to change it just for the installer processes. The `java -version` output does not have `beta` in it so it is definitely not a nightly build. Here is the contents of the 8u292 arm32 tarball from adoptopenjdk:
```
root@odroid:/ssd/sxa# tar tvfz OpenJDK8U-jdk_arm_linux_hotspot_8u292b10.tar.gz | head -5
drwxr-xr-x root/root         0 2021-04-23 12:31 jdk8u292-b10-aarch32-20210423/
-r--r--r-- root/root     19274 2021-04-23 12:31 jdk8u292-b10-aarch32-20210423/LICENSE
-rw-r--r-- root/root  52755666 2021-04-23 12:31 jdk8u292-b10-aarch32-20210423/src.zip
drwxr-xr-x root/root         0 2021-04-23 12:31 jdk8u292-b10-aarch32-20210423/jre/
-r--r--r-- root/root     19274 2021-04-23 12:31 jdk8u292-b10-aarch32-20210423/jre/LICENSE
```
I would hope we'd be able to copy with an alternate top level directory in the scripts. For the previous packages (at least for debian) it installed into a path `/usr/lib/jvm/adoptopenjdk-8-hotspot-armhf` despite that not being the name of the top level directory in the `.tar.gz` file, so we had been doing some translation on the name anyway. Can we do the same now?

**Comment by sophia-guo** [comment]
@sxa I'm not asking to do the change just for the installer processes. Just want to confirm that the issue I hit is expected or not. Did you mean arm jdk8 is using different repository from jdk11 and up? I didn't hit the similar issue with jdk11 and up.

**Comment by sophia-guo** [comment]
Using target arm32 looks fine with Suse. However with Redhat got the error `xargs: invalid number "%{_smp_build_ncpus}" for -P option` . Similar to issue https://bugzilla.redhat.com/show_bug.cgi?id=1096480. Tried with Fedora 34 got same issue. Fedora 35 got update`executor failed running [/bin/sh -c dnf update -y && dnf install -y rpmdevtools rpm-sign rpmlint gnupg2 wget tar dpkg findutils]: exit code: 1
` didn't bother to figure out which update have the issue. 

```
RPM build errors:
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-lto /usr/bin/strip
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
error: Bad exit status from /var/tmp/rpm-tmp.lPSnk9 (%install)
```

**Comment by sophia-guo** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1839372 tried with armv7l works fine.

**Comment by sophia-guo** [comment]
Going forward it would be great to update the jdk8 arm32 tar file's directory name to be as other versions and platforms.  https://github.com/adoptium/temurin-build/issues/2795

**Comment by sxa** [comment]
> Did you mean arm jdk8 is using different repository from jdk11 and up? I didn't hit the similar issue with jdk11 and up.

Correct. it comes from https://github.com/adoptium/aarch32-jdk8u instead of https://github.com/adoptium/jdk8u and there are no plans to merge the aarch32 JIT support into the main codebase unfortunately.

**Comment by sxa** [comment]
> Using target arm looks fine with Suse. However with Redhat got the error `xargs: invalid number "%{_smp_build_ncpus}" for -P option` . Similar to issue https://bugzilla.redhat.com/show_bug.cgi?id=1096480.

Can we try overriding the `--target` to be `armv7l-linux` instead of `arm` and see if that fixes it, which sounds from the comments in that bug that it might resolve the problem.

**Comment by sxa** [comment]
(Just as an FYI due to some memory constraints I can't currently build the `.deb` for arm32 at the moment either)
