### ISSUE TITLE
Missing JDK 17 packages from deb/rpm repos.

### ISSUE THREAD

**Issue by PhonicUK** [adoptium/installer#394]
Some while ago the Adoptium (then AdoptOpenJDK) team published official DEB/RPM repos:

https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e

These work fine up to 16, but there are no packages for 17.

**Comment by sxa** [comment]
We are in the process of setting up the Adoptium repository but it's not quite ready yet. The work is being tracked under [#linuxNew](https://github.com/adoptium/installer/issues/330) with a few other sub-tasks in this repository, so I'm going to close this as a duplicate.
