### ISSUE TITLE
Change adoptium-ca-certificates packages property deb.architecture from any to all in Artifactory Debian repository

### ISSUE THREAD

**Issue by nudgegoonies** [adoptium/installer#400]
The package adoptium-ca-certificates is a dependency of the Temurin debian packages but cannot be found in the Artifactory Debian repository.

Please change adoptium-ca-certificates packages property deb.architecture from any to all in Artifactory Debian repository.

Background:
* any is for Debian source packages that contain sources that are compiled for different architectures. The resulting binary packages then get i386, amd64 etc.
* all is for Debian binary packages that contain only scripts or files that can be installed on all architectures. So there is one package for all architectures.

**Comment by gdams** [comment]
My bad - thanks for spotting this.

For future reference this was the command I used to publish them:

```bash
curl -u adoptium-bot:<password> -XPUT "https://adoptium.jfrog.io/artifactory/deb/pool/main/a/adoptium-ca-certificates/adoptium-ca-certificates_1.0.0-1_all.deb;deb.distribution=stretch;deb.distribution=buster;deb.distribution=bullseye;deb.distribution=xenial;deb.distribution=bionic;deb.distribution=focal;deb.distribution=groovy;deb.distribution=hirsute;deb.component=main;deb.architecture=all" -T adoptium-ca-certificates_1.0.0-1_all.deb
```

**Comment by gdams** [comment]
@nudgegoonies please can you confirm that this is now fixed and close?

**Comment by nudgegoonies** [comment]
@gdams Yes, this works now. I can install temurin 11 and 17. For temurin 8 see https://github.com/adoptium/installer/issues/400
