### ISSUE TITLE
Temurin 8 debian packages cannot be found in Artifactory debian repository

### ISSUE THREAD

**Issue by nudgegoonies** [adoptium/installer#401]
The temurin debian packages cannot be found in Artifactory debian repository. The deb.component and deb.distribution properties of the temurin-11-jdk packages and temurin-17-jdk amd64 packages are correct. But the deb.architecture property of the temurin-8-package is wrong. It has two values i386 and amd64. Maybe this breaks the package index?

Also this directory in the index looks strange. Maybe because of the above problem?
https://adoptium.jfrog.io/ui/repos/tree/Properties/deb/dists/stretch;buster;bullseye;xenial;bionic;focal;groovy;hirsute

Anyway, i can run apt-get update with correct component and distribution and can find the temurin 11 and 17 packages:
```
deb https://adoptium.jfrog.io/artifactory/deb bullseye main
```
```
root@a379e08698e9:/# apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease     
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://adoptium.jfrog.io/artifactory/deb bullseye InRelease [5789 B]
Get:5 https://adoptium.jfrog.io/artifactory/deb bullseye/main amd64 Packages [942 B]
Fetched 6731 B in 1s (4883 B/s)  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```
```
root@a379e08698e9:/# apt search temurin
Sorting... Done
Full Text Search... Done
temurin-11-jdk/bullseye 11.0.13.0.0+8-1 amd64
  Eclipse Temurin 11 JDK

temurin-17-jdk/bullseye 17.0.1.0.0+12-1 amd64
  Eclipse Temurin 17 JDK
```
But they cannot be installed because of this property problem:
https://github.com/adoptium/installer/issues/400

**Comment by gdams** [comment]
@nudgegoonies thanks for the bug report, we're a little while off being fully stable here but I am pushing up the JDK8/17 packages for all platforms now

**Comment by nudgegoonies** [comment]
Thanks a lot. I can now install Temurin 8,11 and 17 on Debian 9,10 and 11.

**Comment by gdams** [comment]
Closing as all Debian packages have now been published
