### ISSUE TITLE
SLES RPMs missing from Repo?

### ISSUE THREAD

**Issue by davshapi** [adoptium/installer#420]
The document at https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/ has:
"Import the RPM repo making sure to change the openSUSE version if you are not using OpenSUSE 15.2. RPM’s are also available for SLES 12 and 15."

In looking at https://packages.adoptium.net/ui/repos/tree/General/rpm, there are OpenSUSE RPMs available, but there don't appear to be any SLES RPMs, for either SLES 12 or SLES 15.  Have SLES RPMs been produced, but are just missing from the repo, or is the documentation in error, and there are no SLES RPMs being made available?

**Comment by karianna** [comment]
@gdams - I think the docs are incorrect, I don't see any SLES RPMs in the source code unless its a case of 'you can use SUSE ones in their place?' (doubtful).

**Comment by gdams** [comment]
We likely need to add the sles versions to the publish scripts. CC @sophia-guo
