### ISSUE TITLE
Define Operating Systems that Adoptium/Temurin will formally support

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#421]
Eclipse Adoptium follows the guideline of officially supporting Long Term Support (LTS) versions of operating systems, and OpenJDK for well supported architectures. By default, Eclipse Adoptium will not support End Of Life (EOL) versions of operating systems, OpenJDK or poorly supported architectures unless specific Working Group member(s) choose to do so. For an up to date list of supported platforms and OpenJDK versions please see https://adoptium.net/supported_platforms.

We are missing an equivalent list of supported installers / specific operating systems, not sure yet how we generated/create that listing.  This issue is here to cover that.  Strawperson as of Jan 19th 2022:

Primary

* Alpine 3.15
* CentOS 6 - EOL (but x86-64 is supported by RH)
* CenrtoOS 7.x, 8.x
* Ubuntu 20.04 LTS
* Mac OS X 10.14, 11.0+, 12.0+
* MS Windows 10+, 11+, Server 2019+

Secondary

* AIX 7.2SP5+
* SLES?  SUSE?
* Solaris 10?

**Comment by karianna** [comment]
See also #420 #330 #412 and many others

**Comment by jerboaa** [comment]
Do we have an Alpine installer? If so, that's news to me.

I'd be in favour of removing CentOS 6 support for installers. Yes, it's still around, but every "supported" installer should be at least tested that it works on such OS. If we add too many we get infra/test overhead explosion. Perhaps a suitable work-around would be to publish the SRPM which users could then rebuild themselves on those platforms?

**Comment by karianna** [comment]
> Do we have an Alpine installer? If so, that's news to me.
> 
> I'd be in favour of removing CentOS 6 support for installers. Yes, it's still around, but every "supported" installer should be at least tested that it works on such OS. If we add too many we get infra/test overhead explosion. Perhaps a suitable work-around would be to publish the SRPM which users could then rebuild themselves on those platforms?

Not sure on Alpine either actually.

**Comment by sxa** [comment]
> Do we have an Alpine installer? If so, that's news to me.

Similarly, we do not provide any native installers for AIX or Solaris

> If we add too many we get infra/test overhead explosion

For once, I'm not too concerned about this in this scenario. The install testing can be done in docker containers so the overhead isn't too bad IMHO, especially if you're testing on quite a few different levels anyway.

> publish the SRPM which users could then rebuild themselves on those platforms?

Yeah that's certainly worth considering as an option :-)
