### ISSUE TITLE
I have also a question about [crypto-policies](https://gitlab.com/redhat-crypto/fedora-crypto-policies): Is it planned to autoconfigure the installed Eclipse Temurin JDK to use the system-wide configured crypto-policies?

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#424]
> > I have also a question about [crypto-policies](https://gitlab.com/redhat-crypto/fedora-crypto-policies): Is it planned to autoconfigure the installed Eclipse Temurin JDK to use the system-wide configured crypto-policies?
> 
> We do not have that in the plan at the moment.

Thanks, @sxa.

The Red Hat distribution of OpenJDK (`java-11-openjdk` package) on RHEL is automatically using the system-wide crypto-policies as far as I know. Probably they configure this behavior in a similar way like you configure the usage of the system certificate store [here](https://github.com/adoptium/installer/blob/bef5de533d56a54a6873a9899ec5308b5a1169a9/linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec#L179).

If it's currently not on the plan - how can I request a feature request for this?

_Originally posted by @maksymgendin in https://github.com/adoptium/installer/issues/330#issuecomment-1026713083_

**Comment by maksymgendin** [comment]
Any news on this? 🙏

**Comment by karianna** [comment]
@maksymgendin At this stage no.  Red Hat Builds of OpenJDK do support this and at some stage they may upstream the patches required for other vendors to also be able to implement this.

**Comment by maksymgendin** [comment]
A bit sad about the unknown timelines. Thanks for your reply, @karianna.
