### ISSUE TITLE
Artifactory instance of packages.adoptium.net does not contain Temurin but shows old AdoptOpenJDK packages

### ISSUE THREAD

**Issue by nudgegoonies** [adoptium/installer#434]
See the IP addresses:
```
❯ host packages.adoptium.net
packages.adoptium.net is an alias for packages-adoptium-net.customers.jfrog.net.
packages-adoptium-net.customers.jfrog.net is an alias for endpointdns-gcprod-use1-lb.jfrog.io.
endpointdns-gcprod-use1-lb.jfrog.io has address 34.139.10.89

❯ host adoptopenjdk.jfrog.io
adoptopenjdk.jfrog.io is an alias for endpointdns-gcprod-use1-lb.jfrog.io.
endpointdns-gcprod-use1-lb.jfrog.io has address 34.139.10.89
```
There is no t directory with the temurin packages anymore in both artifactory instances:
https://adoptopenjdk.jfrog.io/ui/repos/tree/General/deb/pool/main
https://packages.adoptium.net/ui/repos/tree/General/deb/pool/main

Please take a look! This is critical because all mirrors and remote-repos out there, including our own, don't show temurin packages anymore. Please make the temurin packages available under packages.adoptium.net again.

Could it be that a cname switch of your Artifactory instances has gone wrong?

**Comment by nudgegoonies** [comment]
@gdams Thank you very much :+1:
You can close the other ticket as duplicate. I was unsure where the to create the issue.

**Comment by karianna** [comment]
We believe so yes

**Comment by cronicc** [comment]
This issue also exposes potential supply chain security implications if the instructions from https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/ are followed.

In the instructions the GPG pubkey is downloaded from the same source as the package repository and now has changed from fingerprint 3B04D753C9050D9A5D343F39843C48A565F8F04B to the old AdoptOpenJDK key with fingerprint 8ED17AF5D7E675EB3EE3BCE98AC3B29174885C03.

The instructions don't protect against package repository takeover as the key fingerprint is never verified.

We're it not for the fact that the Sectigo intermediate certificate currently required is not included in `ca-certificates` and the temurin packages are not included in the repository it would be possible to install potentially malicious binaries without noticing.

I'd recommend to update the instructions to either:
- Verify the GPG key fingerprint after downloading it from artifactory and before importing it to the apt trusted store
- Retrieve the GPG key from a keyserver using the fingerprint, then import it to the apt trusted store

This problem also applies to yum and maybe zypper.

**Comment by gdams** [comment]
This should now be resolved, please let me know if the problem continues to occur! Closing for now

**Comment by nudgegoonies** [comment]
Thank you - works fine again!
