### ISSUE TITLE
Consider creating APK files

### ISSUE THREAD

**Issue by gdams** [adoptium/installer#442]
Now that packages.adoptium.net is live we should consider build apk installers for the alpine builds

**Comment by lfvjimisola** [comment]
This would help out the community a lot. There are so many of us using alpine in CI/CD and for Kubernetes nowadays. Being able to install using apk instead of wget/curl a tarball etc would make is so much easier.

**Comment by gdams** [comment]
closing in favour of https://github.com/adoptium/installer/issues/220
