### ISSUE TITLE
temurin-17-jdk not providing debug symbols

### ISSUE THREAD

**Issue by noblehelm** [adoptium/installer#443]
As I was trying to attach a profiler (AsyncProfiler) to a running SpringBoot aplication using the recently released temurin-17-jdk for ubuntu repositories (running Ubuntu 20.04) here, I got an error message as follows:
```
[WARN] Install JVM debug symbols to improve profile accuracy
[ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?
```
Which says to me that this new JDK build does not contain debug symbols? Is it a bug, or are they're really not going to be provided?
The strange thing is that the compiled binaries from the adoptium.net website does contain debugsymbols, which I'll have to use (albeit at a "slight loss" of the update-alternatives to switch between versions). Image below does show the difference; temurin-17-jdk is from the new Ubuntu repository, and **adoptium-17-hotspot-amd64** is from the website
![image](https://user-images.githubusercontent.com/5214283/155607109-c57087ad-1424-4b04-a44b-06b3943d3497.png)

**Comment by sxa** [comment]
Confirmed. Apparently the files are being stripped during the production of the installers, which is news to me ... 😖

**Comment by tellison** [comment]
Just as a heads-up, many descriptions of the strip problem also report possibility of overriding [`dh_shlibdeps`](https://man7.org/linux/man-pages/man1/dh_shlibdeps.1.html) if private libraries are removed during packaging. I don't think we have that problem, but mentioning it here in case it comes up later.
