### ISSUE TITLE
Enable Architecture-Specific Installer Shipping

### ISSUE THREAD

**Issue by adamfarley** [adoptium/installer#446]
**Summary**

Enable us to ship Linux installers for a specific subset of architectures.

**Reasoning** 

Our need to ship installers on all architectures is holding us back for the January 2022 release, as arm32 is blocked.

**Useful Links**

https://github.com/adoptium/adoptium/issues/104#issuecomment-1026073992

**Comment by smlambert** [comment]
dup of 459 (will close this one as the other has had more comments made to it)
