### ISSUE TITLE
Update releasing-linux-installer-packages documentation

### ISSUE THREAD

**Issue by smlambert** [adoptium/installer#449]
https://github.com/adoptium/installer#releasing-linux-installer-packages seems to still reference old instructions and release binaries repos.  We should remove information that is out of date, and link to any new documentation that was added around the "linuxNew" installers work.  

Also consider renaming dirs, so that linux -> linuxOld or is removed and linuxNew -> linux.

**Comment by sxa** [comment]
Also need clarity on what to do if you need to repackage and release an update of the same version with an installer fix.

**Comment by karianna** [comment]
I think @zdtsw has updated the docs, Wen, are you able to confirm?

**Comment by zdtsw** [comment]
releasing.md in temurin-build is the last place we need to update

**Comment by karianna** [comment]
> releasing.md in temurin-build is the last place we need to update

OK, I have a PR out for that so we can close this
