### ISSUE TITLE
uninstall OpenJDK 11 from Mac

### ISSUE THREAD

**Issue by MichaelBonfanti** [adoptium/installer#454]
I would like to know if it is possible to uninstall OpenJDK 11 from Mac, as perative system I have MacOS Catalina and the file path and / Library / Java / JavaVirtualMachines /temurin-11.jdk, the version of the JDK and jdk-11.0.14.1 + 1 and downloaded from here https://adoptium.net/temurin/releases.

**Comment by karianna** [comment]
Yes you can.  See (https://adoptium.net/installation/) for details using `brew` (recommended) else you can simply delete `/ `sudo rm -rf /Library/Java/JavaVirtualMachines/temurin-11.jdk`
