### ISSUE TITLE
Update linuxNew pipeline to be able to push subset of platforms

### ISSUE THREAD

**Issue by smlambert** [adoptium/installer#459]
Currently the recently added linuxNew pipeline only supports pushing all platforms in one shot.  It should be enhanced to be able to support pushing singular platforms or a subset of them as they become available which better reflects the release process to date.

**Comment by zdtsw** [comment]
To be more clear about the requirement in this ticket:

change from the current input of job

- jdk version
- distro: redhat|debian|suse

to new input:

- jdk version
- arch selection: x64, ppc64le, armv7l, aarch64,  s390x(when jdk!=8) and x32/i386(when distro==debian)

**Comment by karianna** [comment]
https://github.com/adoptium/installer.git is where it's getting the scripts from which is correct.

**Comment by zdtsw** [comment]
i randomly clicked to  https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/103/
and also https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/115/

**Comment by karianna** [comment]
Try https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/119/ and the currently running one https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/120/ I think they're OK.

**Comment by jiekang** [comment]
Is https://github.com/adoptium/installer/issues/446 addressing the same issue as this one? Maybe close as duplicate?

**Comment by zdtsw** [comment]
> Is #446 addressing the same issue as this one? Maybe close as duplicate?

looks like duplicated issue

**Comment by smlambert** [comment]
Yes both issues appear to be the same, it was raised in release retrospectives and I was unaware that Adam had raised an issue already.  I'll close the earlier one as this one has had more activity on it.

**Comment by smlambert** [comment]
Has this issue been addressed?  Moving it to August plan, but please link relevant PRs if its partially or fully fixed.

**Comment by zdtsw** [comment]
The original PR is https://github.com/adoptium/installer/pull/472
and the job running with PR's code https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/ (up to build number 139)

**Comment by sxa** [comment]
> Has this issue been addressed?

@smlambert I think it would be useful to have @sophia-guo 's input on this since I was under the impression from a conversation recently that she had a job that was capable of doing this already (possibly the job in the previous comment?)  but it wasn't in the main documented pipelines, so it would be useful if she could migrate that functionality to address this so we can all do it :-)

**Comment by smlambert** [comment]
Yep, Sophia should be back from vacation shortly and can weigh in on this one then.

**Comment by sophia-guo** [comment]
My branch is just a hack. So let's working on https://github.com/adoptium/installer/pull/472

**Comment by zdtsw** [comment]
since the code update wont reflect the config of old jenkins job [adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/)
create a new one named[ "adoptium-packages-linux-pipeline_new"](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/)

updated job description

**Comment by sophia-guo** [comment]
@zdtsw I don't understand of the reason to create a new jenkins job for this. Couldn't be done by update the configuration of [adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/)?

**Comment by zdtsw** [comment]
> @zdtsw I don't understand of the reason to create a new jenkins job for this. Couldn't be done by updating the configuration of [adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/)?

We can us the same one as well, but I was thinking if we want to rollback to the old one, we can check out the last working SHA1 in that job. that is only for a short period of time for migration. when everything is working, the old job can be removed and only use the _new one (then rename it)

**Comment by zdtsw** [comment]
verified this feature in 2022 Oct release and it works 
- build package by one platform of one package type 
- build packages by all platforms of one package type
