### ISSUE TITLE
Official PPA repos failing on Ubuntu Impish 21.10

### ISSUE THREAD

**Issue by abnayak** [adoptium/installer#476]
I'm trying to install Temurin JDK on PopOS 21.10 which is based on Ubuntu 21.10 Impish by following the instructions [here](https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/). "apt update" command is failing with following 
error:

```
Reading package lists... Done
E: The repository 'https://packages.adoptium.net/artifactory/deb impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Also, is there any effort to make this package part of official Ubuntu repo as adding keys with "apt-key add -" is a security risk if not done cautiously.

**Comment by karianna** [comment]
@abnayak We'll need to decide if 21.10 is going to be officially supported.  For now we only support LTS releases, e.g. 20.04 and 22.04.  Are you able to upgrade to 22.04?

**Comment by abnayak** [comment]
@karianna Thanks for taking a look at the issue. Upgrading my server OS to get a specific JDK package seems little unreasonable to me.

**Comment by karianna** [comment]
> @karianna Thanks for taking a look at the issue. Upgrading my server OS to get a specific JDK package seems little unreasonable to me.

As a quick workaround you can simply download a tar.gz from our site and install that whilst we discuss non-LTS support

**Comment by sxa** [comment]
I think with 20.10 going out of support in July it is highly unlikely that we would add it now that 22.04 LTS has been released.
Having said that, I was quite surprised that no-one asked for 21.10 support in the last few months - this is the first request that I am aware of.

You could replace `impish` with `jammy` in your `/etc/apt/sources.list.d/adoptium.list` which should allow it to install ok (I've just tried it in a docker container);
```
root@3b21ffd093b7:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
root@3b21ffd093b7:/# java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
root@3b21ffd093b7:/# 
```
The caveat, of course, is that Adoptium has not performed any testing on that release so we cannot vouch for its quality on there, but I would not expect you to hit any problems.

**Comment by abnayak** [comment]
@karianna as per your suggestion I did the OS upgrade though I was very hesitant to do so. Luckily nothing broke after the upgrade.

Thanks @sxa for providing intermediate solution. Ubuntu ships with Oracle OpenJDK package as part of the official PPA, may be many installed that and didn't bother to report this issue. 

I don't know why installing JDK has been so painful all these years and now with so many variation of JDKs, I spend good 1-2hour figuring out which JDK to install and even then ran into above issue.
