### ISSUE TITLE
Can I install RPM together with Oracle JDK RPM?

### ISSUE THREAD

**Issue by ygxxii** [adoptium/installer#477]
The [documentation](https://adoptium.net/installation/linux/) didn't mention that if we can install **adoptium RPM** together with **Oracle JDK RPM**.

[This Fedora old doc](https://web.archive.org/web/20220104133304/https://docs.fedoraproject.org/en-US/quick-docs/installing-java/) said that **Red Hat OpenJDK RPM** is not compatible with **Oracle JDK RPM**:

> Do NOT use Oracle rpms as these are NOT compatible with fedora/openjdk packages. Download the tar.gz archive instead, unpack it somewhere and set to path if necessary.

Is it also happen on **adoptium RPM** ?

Because of some reason, our system can not remove the **Oracle JDK 8 RPM**. So, can I:

- Install **Oracle JDK 8 RPM** +  **adoptium 8 RPM** (same major version) ?
- Install **Oracle JDK 8 RPM** +  **adoptium 11 RPM** (cross major version) ?

**Comment by karianna** [comment]
@ygxxii You should be able to do so yes.  Please try on a test system first and reopen.
