### ISSUE TITLE
MSI installed name should distinguish between JDK/JRE

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/installer#525]
Similar thread #290

In the Add/Remove programs apps list, if a user has both an jdk/jre installed, they both show up with the same project/app name (2 entries with the same name). It would be nice to have a jdk/jre portion added to the name. If we can make the solution generic so that other implementations get the change as well that would be appreciated.

**Comment by sxa** [comment]
@douph1 @steelhead31 FYI

**Comment by steelhead31** [comment]
@AdamBrousseau  
  
Is this specific to a particular JDK / version of Windows? I've just done a quick test with jdk17 and Windows 11, and the 2 MSI installers do create seperate entries.  
 

![](https://mail.google.com/mail/u/0?ui=2&ik=15072974fc&attid=0.1&permmsgid=msg-f:1745678461572633335&th=1839e54fd21652f7&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ8UHR54U4kiuye8ypFKMfAfVMIupj74-BQNd_nHo5vFI8sKlEmiOhJZOaq-dKHI-Jf8w3zG7pNgTxh5AzqwU_82n7YeQspQMiywvtGjBVgRoJXTJznzlCag3zo&disp=emb)

**Comment by AdamBrousseau** [comment]
Ok I didn't realize Temurin already had this. My concern is with the Semeru binaries. Briefly looking at the code I don't see how Temurin has the jre/jdk in the name but we know how to make the change for Semeru.
