### ISSUE TITLE
remove zypper update in the test: we do not test package management function (false alarm) and it takes longer time to finish case

### ISSUE THREAD

**Issue by zdtsw** [adoptium/installer#549]
similar to https://github.com/adoptium/installer/pull/542
and spot failed case because of this
- change is for jdk19 but jdk17 suse failed https://github.com/adoptium/installer/runs/9285518023#r9
- change is for jdk17 but jdk19_suse failed https://github.com/adoptium/installer/pull/534/checks?check_run_id=9285370789
- change for jdk8 failed on jdk17 19 suse https://github.com/adoptium/installer/actions/runs/3392236390/jobs/5638203391 

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">3</strong><span> </span>tests were completed in<span> </span><strong style="box-sizing: border-box; font-weight: 600;">126s</strong><span> </span>with<span> </span><strong style="box-sizing: border-box; font-weight: 600;">2</strong><span> </span>passed,<span> </span><strong style="box-sizing: border-box; font-weight: 600;">1</strong><span> </span>failed and<span> </span><strong style="box-sizing: border-box; font-weight: 600;">0</strong><span> </span>skipped.</p>

Test suite | Passed | Failed | Skipped | Time
-- | -- | -- | -- | --
packaging.ZypperOperationsTest | 2 | 1 |   | 126s

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><g-emoji class="g-emoji" alias="x" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;"><img class="emoji" alt="x" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png" style="box-sizing: content-box; border-style: none; width: 1em; height: 1em; max-width: none; background-color: transparent; vertical-align: text-top;"></g-emoji> <a id="user-content-r11s0" href="https://github.com/adoptium/installer/runs/9285370789#r11s0" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">packaging.ZypperOperationsTest</a></h3><div class="snippet-clipboard-content notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; margin-top: 0px; margin-bottom: 16px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0px; margin: 0px; background: transparent; border-radius: 6px; word-break: normal; white-space: pre; border: 0px; display: inline; overflow: visible; line-height: inherit; overflow-wrap: normal;">❌ opensuse/leap:15.3
	org.opentest4j.AssertionFailedError:
✔️ opensuse/leap:15.4
✔️ registry.suse.com/suse/sle15:latest</code></pre></div>3 tests were completed in 126s with 2 passed, 1 failed and 0 skipped.

Test suite	Passed	Failed	Skipped	Time
[packaging.ZypperOperationsTest](https://github.com/adoptium/installer/runs/9285370789#r11s0)	2heavy_check_mark	1x		126s
x [packaging.ZypperOperationsTest](https://github.com/adoptium/installer/runs/9285370789#r11s0)
❌ opensuse/leap:15.3
	org.opentest4j.AssertionFailedError:
✔️ opensuse/leap:15.4
✔️ registry.suse.com/suse/sle15:latest

**Comment by gdams** [comment]
closed by https://github.com/adoptium/installer/pull/551
