### ISSUE TITLE
The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb jammy Release' does not have a Release file.

### ISSUE THREAD

**Issue by karianna** [adoptium/installer#579]
E: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb jammy Release' does not have a Release file.

Jan/8/2023

_Originally posted by @Splarkszter in https://github.com/adoptium/infrastructure/issues/1399#issuecomment-1374901434_

**Comment by karianna** [comment]
https://adoptopenjdk.jfrog.io/ui/native/deb/dists/ does not appear to have a jammy folder

**Comment by karianna** [comment]
@gdams Bug in our upload process?

**Comment by gdams** [comment]
@Splarkszter please migrate to using https://packages.adoptium.net. For the most up to date set of instructions please see https://adoptium.net/installation/linux/#_deb_installation_on_debian_or_ubuntu
