### ISSUE TITLE
Upload of JRE8 For Arm32 / Redhat / Suse platforms does not work.

### ISSUE THREAD

**Issue by steelhead31** [adoptium/installer#608]
The installer pipeline does not upload JRE8 artifacts to artifactory, although it builds the rpms with the correct names as shown in the following jobs..

https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/250/
& 
https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/249/

The upload logs show..

Upload artifacts for 8 - armv7l - RedHat
[Pipeline] echo
Prepare for null.rpm
[Pipeline] findFiles
[Pipeline] sleep
Sleeping for 2 sec
[Pipeline] echo
Prepare for null.rpm
[Pipeline] findFiles
[Pipeline] sleep
Sleeping for 2 sec
[Pipeline] echo
Prepare for null.rpm

**Comment by zdtsw** [comment]
so the reason it prints "sleep" is because it could not find the file which should be uploaded
this prints was done by me when we had some issue to upload artifact in 2022.Oct release.

**Comment by steelhead31** [comment]
A workaround for JRE8 was to add a version of armv7hl to the arch parameter list, this has allowed the rpm's to be uploaded. this will need a proper fix ahead of the next release.

**Comment by ascheman** [comment]
Perhaps the other way around: Drop `arm7hl` in favour of `arm7l` (which is used anywhere else)?

**Comment by sxa** [comment]
> A workaround for JRE8 was to add a version of armv7hl to the arch parameter list, this has allowed the rpm's to be uploaded. this will need a proper fix ahead of the next release.

I'm surprised that was different between JDK8 and later versions - RPM distros use `armv7hl` for the 32-bit ARM that we support. Debian based packages use `armhf` so that should be consistent across versions, so maybe there's a path that isn't picking up the right thing.

**Comment by steelhead31** [comment]
This is correct and working in the current jenkins file. so closing this as its been fixed.
