### ISSUE TITLE
Alpine Linux Repository Temurin JDK and JRE `java.lang.SecurityException: Can not initialize cryptographic mechanism`

### ISSUE THREAD

**Issue by Jeeppler** [adoptium/installer#613]
While testing the Alpine Linux installer of JRE and JDK. 

I realized that our application does not work with either JRE or JDK. The error cause is: `java.lang.SecurityException: Can not initialize cryptographic mechanism`. I documented the issue here: https://github.com/mercedes-benz/sechub/issues/1794. 

JRE and JDK for Debian work well. My expectation would be, that what works on Debian should work on Alpine Linux as well.

Another user found the same problem and described it in #572. However, adding a security policy for JDK did not solve the problem entirely for me. In addition, I would expect, that installing JDK or JRE with  `apk add temurin-17-jdk` or `apk add temurin-17-jre` would result in an usable installation.

**Comment by ascheman** [comment]
Thanks for raising this @Jeeppler, I was just starting to investigate this last night without seeing your issue.
Please assign this to me, @smlambert.

**Comment by ascheman** [comment]
Investigation shows that both JDK and JRE installers do not contain the complete contents of the underlying tarball, e.g., for JDK-17 the files/directories legal, conf, release, jmods, man, and NOTICE are not put into the resulting APKs.

Then the missing `conf/security` directory contents lead to errors with cryptograpic APIs as used by Tomcat.

Comparing the Adoptium APK builds with the [OpenJDK builds of the Alpine maintainers](https://git.alpinelinux.org/aports/tree/community/openjdk17/APKBUILD?h=3.17-stable) shows that the Adoptium builds are incomplete.

**Comment by ascheman** [comment]
@karianna / @smlambert IMHO this is not an _enhancement_ but rather a _bug_. Could you please relabel?

**Comment by ascheman** [comment]
Currently this seems to be missing for JDK major versions 11, 17, 19 (8 does not introduce APK subpackages so far).

I see two options to solve this

1. Just add the missing parts to the APK builds for the respective JDKs/JREs, i.e., add at least the `conf/` part from the tarball.
2. Align the JDK/JRE builds with the [OpenJDK builds by Alpine](https://git.alpinelinux.org/aports/tree/community/openjdk17/APKBUILD?h=3.17-stable), i.e., re-unify JDK and JRE builds into a single step and provide several subpackages: jmods, demos, doc, jre, src, jre-headless, jdk, with respective APK dependency management.

The latter would enable misc. install options, e.g., jre, jre+docs, jdk (includes jre), jdk+src, ...

**Comment by karianna** [comment]
@gdams possibly an overzealous exclude filter?

**Comment by ascheman** [comment]
@karianna IMHO it's the the other way round: the missing parts should have been explicitly included.

**Comment by karianna** [comment]
Yeah our deps knowledge of Debian/CentOS/Suse is > Alpine

**Comment by ascheman** [comment]
I am just learning this as well (the hard way, obviously).

**Comment by ascheman** [comment]
If we opt for solution no. 2 maybe the only remaining question is whether we should distinguish between jre and jre-headless, as discussed already in the [community meeting of 2023-01-18](https://docs.google.com/document/d/1oaU8GA_3F8DDzjeZujY10fiyRS-vKdF5rE0eAhAascY/edit#heading=h.jaht6wmudoa2) (should be subject to some PMC decision).

**Comment by Jeeppler** [comment]
If the JRE is headless it should be clear from the name of the package (`temurin-*-jre-headless`). I am not even sure, whether a non-headless version of the JDK or JRE on Alpine is possible (assumption: graphical libraries required for AWT and Swing are missing).

**Comment by ryanlewis** [comment]
Hi @ascheman , has there been any progress on this issue?
