### ISSUE TITLE
attempting to copy repo

### ISSUE THREAD

**Issue by myrelle22** [adoptium/installer#616]
We have been having issues using your repo.  This is causing us difficulties when attempting to patching or install systems.  I attempted to use wget to get a copy of your repo to avoid the problems with your yum/dnf repo.  I have been unable to do.  We are also unable to use your repo in our dmz.  We must use our own internal.  Please forward instructions for getting a copy of your repo.

**Comment by karianna** [comment]
Our repo is hosted by JFrog.  What difficulties are you having and what part of the world are you in?  Any VPNs in use?
