### ISSUE TITLE
Unable to install temurin

### ISSUE THREAD

**Issue by 4Sven** [adoptium/installer#621]
I'm unable to install temurin because yum errors.

`yum install -v -d 0 temurin-11-jre`

> Loading "extras_suggestions" plugin
> Loading "langpacks" plugin
> Loading "priorities" plugin
> Loading "update-motd" plugin
> Adding en_US to language list
> Config time: 0.567
> Yum version: 3.4.3
> rpmdb time: 0.000
> Setting up Package Sacks
> Adoptium                                                                                                                                                       | 3.0 kB  00:00:00     
> https://packages.adoptium.net/ui/native/rpm/amazonlinux/2/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for Adoptium: Damaged repomd.xml file
> Trying other mirror.
> 
> 
>  One of the configured repositories failed (Adoptium),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Run the command with the repository temporarily disabled
>             yum --disablerepo=Adoptium ...
> 
>      4. Disable the repository permanently, so yum won't use it by default. Yum
>         will then just ignore the repository until you permanently enable it
>         again or use --enablerepo for temporary usage:
> 
>             yum-config-manager --disable Adoptium
>         or
>             subscription-manager repos --disable=Adoptium
> 
>      5. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=Adoptium.skip_if_unavailable=true
> 
> failure: repodata/repomd.xml from Adoptium: [Errno 256] No more mirrors to try.
> https://packages.adoptium.net/ui/native/rpm/amazonlinux/2/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for Adoptium: Damaged repomd.xml file

Operating System is Amazon Linux 2. We are behind a firewall.

This is my adoptium.repo 

> [Adoptium]
> name=Adoptium
> baseurl=https://packages.adoptium.net/ui/native/rpm/amazonlinux/2/$basearch
> enabled=1
> gpgcheck=1
> gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
> proxy=http://xxxxxxxx:yyyy

I tried to get the repomd.xml with curl:

`curl https://packages.adoptium.net/ui/native/rpm/amazonlinux/2/x86_64/repodata/repomd.xml`

> <!doctype html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=importmap-type content=systemjs-importmap><link rel=apple-touch-icon sizes=180x180 href=./apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=./favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=./favicon-16x16.png><link rel=mask-icon href=./safari-pinned-tab.svg color=#f5f5f2><link rel="shortcut icon" href=./favicon.ico><link rel=stylesheet type=text/css href=/ui/webapp/css/vendorStyles.css><link rel=stylesheet type=text/css href=/ui/webapp/css/application.css><script type=systemjs-importmap src=/ui/imports-map/imports.json></script><script src=/ui/externals/import-map-overrides/dist/import-map-overrides.js></script><script src=/ui/externals/systemjs/dist/s.min.js></script><script src=/ui/externals/systemjs/dist/extras/amd.min.js></script><script src=/ui/externals/systemjs/dist/extras/named-exports.min.js></script><link rel=preload href=/ui/externals/vue/dist/vue.min.js as=script><link rel=preload href=/ui/externals/vue-router/dist/vue-router.min.js as=script><link rel=preload href=/ui/externals/jfrog-ui-essentials/dist/jfrog-ui-essentials.umd.min.js as=script><link rel=preload href=/ui/externals/single-spa/lib/umd/single-spa.min.js as=script><base href=/ui/ ><title>JFrog</title><style>@keyframes heartbeatOut{from{opacity:1}50%{opacity:0;transform:scale(.8)}to{opacity:0;transform:scale(.8)}}@keyframes heartbeat{from{transform:scale3d(1,1,1)}50%{transform:scale3d(1.15,1.15,1.15)}to{transform:scale3d(1,1,1)}}.pounding-heart-container{display:none;align-items:center;justify-content:center;position:absolute;left:0;right:0;top:0;bottom:0;z-index:9999999999;background:linear-gradient(132.49deg,#414857 14.17%,#252831 83.36%)}.pounding-heart-container.show-splash{display:flex}.logo{width:130px;-webkit-backface-visibility:hidden;-ms-transform:translateZ(0);-webkit-transform:translateZ(0);transform:translateZ(0)}.logo.pulse{animation:heartbeat 1.7s infinite}.logo.zoom-out{animation:heartbeatOut 150ms forwards}</style><link href=/ui/css/app.3984390b.css rel=preload as=style><link href=/ui/css/chunk-vendors.b50e2d2a.css rel=preload as=style><link href=/ui/js/app.4fbaabb9.js rel=preload as=script><link href=/ui/js/chunk-vendors.5d0db5a9.js rel=preload as=script><link href=/ui/js/preloader.1ff27ea9.js rel=preload as=script><link href=/ui/css/chunk-vendors.b50e2d2a.css rel=stylesheet><link href=/ui/css/app.3984390b.css rel=stylesheet></head><body><div class="pounding-heart-container show-splash"><img class="logo pulse" src=/ui/img/jfrog.8f770bff.svg></div><noscript><strong>We're sorry but jfrog webapp doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=/ui/js/chunk-vendors.5d0db5a9.js></script><script src=/ui/js/app.4fbaabb9.js></script><script src=/ui/js/preloader.1ff27ea9.js></script></body></html>

How can I solve this?

**Comment by karianna** [comment]
https://packages.adoptium.net/ui/native/rpm/amazonlinux/2/x86_64/repodata/repomd.xml appears to be an empty file when using a web browser.

Paging @gdams as I'm not sure we support Amazon Linux directly.

**Comment by sxa** [comment]
Not sure what happened here but I've just tried to reproduce and it works ok, and the repomd.xml mentioned in the previous comment appears to contain valid comment, so I think this issue can be closed. Feel free to reopen if you believe there is still an issue here.
