### ISSUE TITLE
Alpine installer JRE and JDK add support for more architectures

### ISSUE THREAD

**Issue by Jeeppler** [adoptium/installer#628]
# Problem

Currently, the Alpine installer supports only x86_64.

https://github.com/adoptium/installer/blob/8687b392feaeb2cab9b72ab780d6d673ab81609a/linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD#L12

More and more public cloud providers are offering servers based on ARM and with Apple switching to ARM as main architecture more people are using ARM on their computer as well.

Alpine itself supports aarch64, armv7, ppc64le, s390x, x86 and x86_64 (source: https://www.alpinelinux.org/downloads/).

# Solution

Support additional architectures. Starting with `aarch64` bit is probably the most interesting as ARM 64 bit (aarch64) is used in server and laptops (Mac).

**Comment by Jeeppler** [comment]
Related to: #613

**Comment by sxa** [comment]
This has been discussed in the PMC meeting. At the moment we only provide a released version of Alpine on x64 so this code will currently not be used on other architectures as we don't run the packaging step on non-release platforms. When we get to the stage where we have a build on aarch64 (which will be the first one) then we will definitely be updating this accordingly with the ability to package for the architectures which we ship.

Any further information on making Alpine/aarch64 production ready (we have not had any requests elsewhere) will be tracked in https://github.com/adoptium/containers/issues/158

**Comment by Jeeppler** [comment]
@sxa thanks for the explanation and the link to the issue.
