### ISSUE TITLE
Support enable windows installer tests - part 1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/installer#640]
Part 1 of #559 

- [x] Add [create_windows_installer](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/configure) script to source control (in this repo)

- [x] [windows_installer_test jenkins job for initial testing ](https://ci.adoptium.net/view/Test_grinder/job/Windows_Installer_Test/)
- [x] set up wintps tests as part of  aqa-tests functional tests: https://github.com/adoptium/installer/pull/630 https://github.com/adoptium/installer/tree/master/test/functional/wintps
- [x] initial update and enhance  in https://github.com/rh-openjdk/WindowsTPS to support tests in jenkins

**Comment by sophia-guo** [comment]
@RadekCap @zzambers I can't add both of you as the assignees. Could you both add by yourself?

**Comment by RadekCap** [comment]
I do not have sufficient access right to assign anybody in this issue.

**Comment by RadekCap** [comment]
According to documentation - https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

we need "anyone with write permissions to the repository, and organization members with read permissions to the repository. "

Who can add them? @smlambert do you know who can?
