### ISSUE TITLE
OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi /quiet switch it is not working.

### ISSUE THREAD

**Issue by GI009** [adoptium/installer#652]
### Please provide a brief summary of the bug

Following documentation in the website for MSI quiet installation on windows it is not working.

MSI is installing fine without /quiet switching

msiexec.exe /i OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10 /quiet

### Please provide steps to reproduce where possible

msiexec.exe /i OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10 /quiet

### Expected Results

Expected to be installed silently but it is not.

### Actual Results

msiexec.exe /i OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10 /quiet

### What Java Version are you using?

OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10

### Did you test with the latest update version?

```Shell
tested with the below versions

OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10
OpenJDK17U-jdk_x64_windows_hotspot_17.0.5_8
```

**Comment by gdams** [comment]
perhaps it's working trying with an `INSTALLLEVEL` specified (as I suspect it's hanging on the feature selection menu)

```bat
msiexec /i <package>.msi INSTALLLEVEL=1 /quiet
```

Let me know if that works?

I do also note in your example that the installer you're trying to install is missing the `.msi` extension (although I suspect that's just a copy-and-paste error?)

**Comment by gdams** [comment]
@GI009 did this fix your issue?
