### ISSUE TITLE
permission denied on jdk-17 even with sudo on latest version of ubuntu

### ISSUE THREAD

**Issue by jake-jpg** [adoptium/installer#677]
while i was trying to install the jdk it all went din up untill i typed in 
sudo echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

wich i was propmted with the error
tee: /etc/apt/sources.list.d/adoptium.list: Permission denied
deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb jammy main

and i was unable to insatall the distro

**Comment by karianna** [comment]
@jake-jpg try with `sudo`

**Comment by sxa** [comment]
Noting that the OP does have `sudo` at the start of the command but it needs to be before the `tee` as that is what writes to the restricted file.

**Comment by jake-jpg** [comment]
@sxa thanks i tried your fix and it seems to be working

**Comment by jake-jpg** [comment]
Thanks @sxa i tried your fix and it seems to be working

**Comment by panych** [comment]
Maybe it's worth a note about 'sudo tee' or snippet update on https://adoptium.net/installation/linux/ for future users.

**Comment by karianna** [comment]
Before we do I'd like to get clarity on whether `sudo` is always required or whether some users just happen to have that file particularly locked down.

**Comment by sxa** [comment]
> Before we do I'd like to get clarity on whether sudo is always required or whether some users just happen to have that file particularly locked down.

Similar to the actual install, the package repository addition will always have to be done as `root` (either with `sudo` or by switching to a root shell first - in which case you don't need the `sudo`).

**Comment by sxa** [comment]
> IMO Could be worth a note about 'sudo tee' on https://adoptium.net/installation/linux/ for future users

There is already a "Tip" near the top of the page that says _"On most Linux systems you must have superuser privileges to install packages such as Temurin. You may need to prefix the commands below with sudo for them to succeed."_ although as you suggest that should probably clarify that it's also required for the repository addition.
