### ISSUE TITLE
Upgrade Wix installers to use V4

### ISSUE THREAD

**Issue by gdams** [adoptium/installer#680]
There's a load of goodness we're missing out on in the wix toolset by staying at V3 but the migration is slightly complicated. I've asked an initial question at https://github.com/orgs/wixtoolset/discussions/7534.

There is also a helpful migration guide: https://wixtoolset.org/docs/fourthree/

@douph1 not sure if you have any experience with V4?

**Comment by douph1** [comment]
not any @gdams :(
I have not run/build with Wix since long long time

**Comment by karianna** [comment]
Assigning to @d3r3kk for his team
