### ISSUE TITLE
Provide Fedora 38 yum repo

### ISSUE THREAD

**Issue by azrdev** [adoptium/installer#690]
artifactory repos for fedora 38 are missing:

```
# /etc/yum.repos.d/ansible_repo:adoptopenjdk.repo.repo
# see <https://adoptium.net/de/installation/linux>
[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/fedora/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
```

yields in yum
>  - Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/38/x86_64/repodata/repomd.xml (IP: 44.240.108.245)

**Comment by jiekang** [comment]
F38 RPMs should be available now (https://packages.adoptium.net/ui/repos/tree/General/rpm/fedora/38/x86_64/Packages) and the link in the original comment is not a 404 anymore.

It was added via https://github.com/adoptium/installer/pull/673 awhile back but I guess builds didn't make it there until the July CPU update.

**Comment by sxa** [comment]
Noting that this was added in https://github.com/adoptium/installer/pull/673/files
