### ISSUE TITLE
MSI-Installer: Text is cut off and not readable

### ISSUE THREAD

**Issue by larsen0815** [adoptium/installer#732]
### Please provide a brief summary of the bug

The help text for at least one element that can be installed is cut off (notice the "..."). 

![Clipboard-1](https://github.com/adoptium/adoptium-support/assets/2345512/9173901e-2a4b-42cc-ba4c-1bc70954ab77)

### Please provide steps to reproduce where possible

- On Windows, start the installer for Temurin JDK 17
- Continue until the page where it is possible to select elements to be installed
- Select "JavaSoft (Oracle) registry keys"
- See text on the right

### Expected Results

Text should be short enough to be fully readable. Or better: Provide a link to a web page that has more information.

### Actual Results

Text is cut off (to be precise: something is left out from the middle) and in this form makes no sense at all.

### What Java Version are you using?

17

**Comment by douph1** [comment]
As noted here 
https://github.com/adoptium/installer/blob/ce1b4858058ff90ca5866db66274d05f780170f7/wix/Lang/OpenJDK.Base.fr-fr.wxl.template#L19

Description must be limited to 255 chars (spec that I found somewhere one time) .

This one on en-us is  258 chars after substituting {vendor_branding}) by "Eclipse Temurin"
In fr-fr around 256 with {vendor_branding}) replaced by "Eclipse Temurin"

I think I remember that the full text is show when the cursor go in top of the text.

Feel free to propose a shorter description for each language to fit into 255 chars

**Comment by adipiciu** [comment]
There is even a validation warning when building the msi:
warning SMOK1076 : ICE03: String overflow (greater than length permitted in column); Table: Feature, Column: Description, Key(s): FeatureOracleJavaSoft

![image](https://github.com/adoptium/installer/assets/13155063/02af4e7a-0135-4e06-82d0-0bfdfb8c2d49)

**Comment by adipiciu** [comment]
I shortened the text under 255 length but it still doesn't show properly.
 ![image](https://github.com/adoptium/installer/assets/13155063/08c48b91-8961-46a0-b76b-a80042774b8c)

**Comment by adipiciu** [comment]
I propose to shorten the string, so it can fit and also to get rid of the validation warning.
If the string cannot fit, it adds ellipsis (...) and you won't understand anything anyway.

@douph1 what do you say?
![image](https://github.com/adoptium/installer/assets/13155063/ce32c4ad-339e-416b-9a7e-673e35fb3daa)

**Comment by karianna** [comment]
> I propose to shorten the string, so it can fit and also to get rid of the validation warning. If the string cannot fit, it adds ellipsis (...) and you won't understand anything anyway.
> 
> @douph1 what do you say? ![image](https://private-user-images.githubusercontent.com/13155063/294709413-ce32c4ad-339e-416b-9a7e-673e35fb3daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDYzNTgsIm5iZiI6MTcwNDYwNjA1OCwicGF0aCI6Ii8xMzE1NTA2My8yOTQ3MDk0MTMtY2UzMmM0YWQtMzM5ZS00MTZiLTlhN2UtNjczZTM1ZmIzZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA1NDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NDUxNGRjNDcwMGU0NGQ4YWMwMmUyNGNiODhmOGFlYjQxOGE1ZDFiNjA1NTI2YzYwMTM4M2ZlODUxOTI0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-gDsWWNpaNIGmkdWHdxvF_Jc-IwfObFagTINR_es7qM)

If you just remove Eclipse or Temurin, would that fit?

**Comment by adipiciu** [comment]
> If you just remove Eclipse or Temurin, would that fit?

Eclipse Temurin is a variable {vendor_branding}. But even if I remove that, it still doesn't fit completely.

![image](https://github.com/adoptium/installer/assets/13155063/33d5bdfe-7a7a-47b3-9fe6-9c032cc5c511)

**Comment by adipiciu** [comment]
This is the maximum we can fit (159 characters)

![image](https://github.com/adoptium/installer/assets/13155063/dad36afb-9eaf-4c98-85f4-8495d8a6bf2c)

**Comment by douph1** [comment]
PR already merged
