### ISSUE TITLE
Artifactory Certificate Validation Failed

### ISSUE THREAD

**Issue by TaffarelJr** [adoptium/installer#734]
Installing Temurin inside a Docker image based on Ubuntu 20.04, I get:

```
The following NEW packages will be installed:
  adoptium-ca-certificates fontconfig-config fonts-dejavu fonts-dejavu-core
  fonts-dejavu-extra java-common libasound2 libasound2-data libfontconfig1
  libfreetype6 libpng16-16 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6
  libxext6 libxi6 libxrender1 libxtst6 p11-kit p11-kit-modules temurin-11-jdk
  temurin-17-jdk temurin-8-jdk x11-common
0 upgraded, 26 newly installed, 0 to remove and 0 not upgraded.
Need to get 423 MB of archives.
After this operation, 879 MB of additional disk space will be used.
Get:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 adoptium-ca-certificates all 1.0.2-1 [2304 B]
Err:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-11-jdk amd64 11.0.20.1.0+1
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 52.218.209.58 443]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 libpng16-16 amd64 1.6.37-2 [179 kB]
Err:3 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-17-jdk amd64 17.0.8.1.0+1
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 52.218.209.58 443]
Err:4 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-8-jdk amd64 8.0.382.0.0+5
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 52.218.209.58 443]
```

I saw #434 and #435; I don't know if this is a repeat of the same issue, or maybe due to the fact I'm running inside a dockerfile. The image I'm building is for a GitHub build runner, so it's got a lot of other APT keys/repos/packages that all install successfully (including `ca-certificates`); this is the only install that fails. Any idea why?

Since it's Docker, I can provide any other information you need about the exact image configuration.

**Comment by karianna** [comment]
Interestingly it's trying to install temurin 8 and temurin 17 - Can you share how you're installing?   Is it one of the DEB archives via the instructions on our website?

**Comment by TaffarelJr** [comment]
Yes, we're installing 3 versions of temurin (8, 11, and 17) because this is a build agent for many applications -- some legacy. I took the code for installing them straight from the website (with some tweaks to keep the lines short). The script is as follows:

```bash
# Download key
URI="https://packages.adoptium.net/artifactory"
FILE=/etc/apt/keyrings/adoptium.asc
curl -fsSLo "$FILE" "$URI/api/gpg/key/public"

# Configure repository
CODENAME=$(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release)
echo "deb [signed-by=$FILE] $URI/deb $CODENAME main" \
| tee /etc/apt/sources.list.d/adoptium.list > /dev/null

# Update package lists
apt-get update -y

# Install JDKs
apt-get install -y --no-install-recommends \
    temurin-8-jdk \
    temurin-11-jdk \
    temurin-17-jdk
```

**Comment by karianna** [comment]
@gdams Can we get some debug logs from JFrog?

**Comment by gdams** [comment]
@TaffarelJr just a thought, does `/etc/apt/keyrings` exist? In a standard Focal installation you need to create that directory first:

```bash
mkdir -p /etc/apt/keyrings
```

**Comment by gdams** [comment]
Also are you running this behind a cooperate proxy?

**Comment by TaffarelJr** [comment]
@gdams Yes we're creating the keyrings dir in a previous script, with this line:

```bash
# Make sure the keyrings directory exists with the correct permissions
install -m 0755 -d '/etc/apt/keyrings'
```

Scripts all run as root -- the default in the `ubuntu:20.04` base image.

We're adding several ATP keys/repos for things like Docker, Kubernetes, Microsoft, Git, Terraform, etc. and all of those work fine. I was expecting temurin to work the same way, but it's not.

**Comment by gdams** [comment]
> ```shell
> # Install JDKs
> apt-get install -y --no-install-recommends \
>     temurin-8-jdk \
>     temurin-11-jdk \
>     temurin-17-jdk
> ```

Hmm very strange, the commands you've provided run fine for me, let me reach out to the JFrog support team and see if they have any ideas

**Comment by gdams** [comment]
can you send me the complete dockerfile so I can copy your exact environment?

**Comment by TaffarelJr** [comment]
I just built the dockerfile on GitHub's public build runners, and it worked fine there as well. So it must be something with my local environment. Can you help me figure out where to look?

I'm on Windows 10 Enterprise, using bash to build linux containers.

```bash
$ docker version
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.22.1 (118664)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by TaffarelJr** [comment]
If it's inside a dockerfile though, I image my machine config shouldn't matter so much -- what's in the dockerfile is what's important, because that's the environment the scripts run in. Yet ... somehow it's not building for me locally.

**Comment by TaffarelJr** [comment]
Perhaps in my case Docker is making URI calls _through_ Windows -- which would mean Windows needs to have the proper root certs to connect to Temurin Artifactory.

Are there instructions for accessing Temurin Artifactory APT source from Windows? I know from linux it wants to install `adoptium-ca-certificates` as a dependency, and I imagine that's what grants access. But if Docker is going through Windows, is there a similar package/cert that I need to install manually in Windows to get it to work?

**Comment by JamesXNelson** [comment]
You definitely need to install the ca certificates. Install `adoptium-ca-certificates` before attempting to install the jdk.
