### ISSUE TITLE
add support for fedora39 installer

### ISSUE THREAD

**Issue by kebeda** [adoptium/installer#739]
https://packages.adoptium.net/artifactory/rpm/fedora/39/ is missing

**Comment by andres-moreno** [comment]
Please add support for Fedora 39. I updated my machine since it is the current Fedora release but then I realized that there is no repository for it.

**Comment by GalaxyVOID** [comment]
You could try https://packages.adoptium.net/artifactory/rpm/fedora/38/  in the meantime while they add support

**Comment by andres-moreno** [comment]
I believe there is now SELinux
<https://guix.gnu.org/en/manual/devel/en/html_node/SELinux-Support.html>.
The binary installer implements the approach which, admittedly, has some
drawbacks per the manual page I linked.

My intention is to remove Guix from my Fedora machine and try this new
updated installer.

Cheers! afm
