### ISSUE TITLE
[MSI-Installers] JavaSoft keys not removed at uninstall

### ISSUE THREAD

**Issue by adipiciu** [adoptium/installer#741]
To reproduce:
- install Temurin 8 after that install Temurin 11 or 17
- uninstall Temurin 11/17 and after that uninstall Temurin 8 : the registry "SOFTWARE\JavaSoft\Java Runtime Environment" keys remains on the system

If you uninstall Temurin 8 and after that uninstall Temurin 11/17 : the registry "SOFTWARE\JavaSoft\JRE" keys remains on the system

Normal behavior should be these keys to be removed after uninstall. 
This happens because the component GUID for the JavaSoft keys are the same for all Temurin versions. This is a bug, because the registry keys are different for Temurin 8 and Temurin 11 or 17. ("SOFTWARE\JavaSoft\JRE" vs "JavaSoft\Java Runtime Environment") 

Solution: the MSI component GUIDs should be different in Temurin 8 than in Temurin 11 or 17.

**Comment by douph1** [comment]
Hi,

>This happens because the component GUID for the JavaSoft keys are the same for all Temurin versions.

I don't think component GUID will be the same as "Guid" is specified as "*" to generate random value.
https://github.com/adoptium/installer/blob/ce1b4858058ff90ca5866db66274d05f780170f7/wix/Main.wxs.template#L138
https://github.com/adoptium/installer/blob/ce1b4858058ff90ca5866db66274d05f780170f7/wix/Main.wxs.template#L142


>Normal behavior should be these keys to be removed after uninstall.

Wix don't suppress the key because there are shared keys by multiple MSI.

https://github.com/adoptium/installer/blob/ce1b4858058ff90ca5866db66274d05f780170f7/wix/Main.wxs.template#L207

As you can read here : https://github.com/adoptium/installer/issues/64 : 
```
And just one note to everyone :

MSI Installer works as is: If a registry key is handled by many installers, it will be removed only when the last installer is uninstalled.

So if we replace the JavaSoft (created by Oracle) key value with an Adopt value it will not delete the JavaSoft key when Adopt is uninstalled and will let the value CurrentVersion (Adopt Value which is missing) as is
```

See https://github.com/adoptium/installer/issues/124 too
 
You have probably other installer who have write to this registry keys before you started to install Temurin 8/11/17 ..

**Comment by adipiciu** [comment]
@douph1 Did you even tried to reproduce using the steps I provided?

Look in the latest installers, same GUID for JRE 8 and JRE 11:
![image](https://github.com/adoptium/installer/assets/13155063/a0454a25-1767-45c1-a971-6b6f9988325c)

Maybe wix is creating the GUIDs automatically from the key path name which is the same. The problem is having the same shared GUID for 2 different registry paths:
SOFTWARE\JavaSoft\Java Runtime Environment
and 
SOFTWARE\JavaSoft\JRE


So, JRE 11 and 17 having the same GUID is ok, because they have the same registry path. But JRE 8 should have a different GUID because it has a totally different registry path. The issue can be easily reproduced by using a clean Windows installation and following the steps from the 1st post.

**Comment by douph1** [comment]
No, sorry I'm not on Windows now.


So it is probably for the same reason as this :

https://sourceforge.net/p/wix/mailman/message/28483068/

      ```
<Component Id="SetOracleJavaSoftKeys" Guid="*">
        <RegistryValue Root="HKLM" Key="SOFTWARE\JavaSoft\[ORACLE_JAVASOFT_BASE_KEY]\[ORACLE_VERSION_KEY]" Name="JavaHome" Type="string" Value="[INSTALLDIR]" KeyPath="yes" />

```
For a Component the Guid is related to the KeyPath.
The KeyPath is this reg key
wich is different for both installer you checked 

=> SOFTWARE\JavaSoft\JRE\11
=> SOFTWARE\JavaSoft\Java Runtime Environment\1.8

But as explain in the link bellow : 
>Properties in the registry path will only be resolved at runtime which means
that the property name is being used for guid generation. 

I assume now that the Key for the KeyPath is literaly "SOFTWARE\JavaSoft\[ORACLE_JAVASOFT_BASE_KEY]\[ORACLE_VERSION_KEY]"


Have you time to propose a PR to fix this ?

Deleting 
    <Property Id="ORACLE_VERSION_KEY" Value="$(var.OracleVersionKey)" />
    <Property Id="ORACLE_JAVASOFT_BASE_KEY" Value="$(var.OracleJavasoftBaseKey)" />
and
Replacing everywhere
[ORACLE_JAVASOFT_BASE_KEY] with $(var.OracleJavasoftBaseKey)
[ORACLE_VERSION_KEY] with $(var.OracleVersionKey)

Thanks

**Comment by adipiciu** [comment]
Yes, that could be a fix.
No one changes the value of ORACLE_JAVASOFT_BASE_KEY at runtime.
```
msiexec.exe /i "OpenJDK8U-jre_x64_windows_hotspot_8u392b08.msi" ORACLE_JAVASOFT_BASE_KEY=xxx.xxx.xxx
```

Even the Oracle msi doesn't use properties for these values, which aren't changing at runtime.

![image](https://github.com/adoptium/installer/assets/13155063/3caf2bf2-241b-476c-b2ea-e277e6478c02)

**Comment by adipiciu** [comment]
I just checked how Correto is doing it. They also don't use runtime properties in the msi installer

![image](https://github.com/adoptium/installer/assets/13155063/7c7bc594-1c5e-42ae-aec2-4bddebf3e274)

**Comment by douph1** [comment]
Yes it is a misunderstanding about variable vs property usage. I agree. It is not needed.

**Comment by douph1** [comment]
@adipiciu can you check that the change merged has fix the bug in latest build please ? if yes we can close the issue.
Thanks

**Comment by adipiciu** [comment]
@douph1 Yes, it fixes the problem for newer builds.
