### ISSUE TITLE
Error: Unable to find a match: Adoptium

### ISSUE THREAD

**Issue by zwilliam12** [adoptium/installer#746]
Hello! After setting up my /etc/yum.repos.d/adoptium.repo as follows, running **sudo dnf clean all**, **sudo dnf update**, and finally **sudo dnf install Adoptium**, I receive the message "No match for argument: Adoptium Error: Unable to find a match: Adoptium"

Additionally, **sudo dnf search Adoptium** finds nothing. It would seem I have a configuration issue even though the repolist command does find Adoptium.

[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/oraclelinux/8/x86_64
enabled=1
gpgcheck=0

I've also tried using the configuration exactly as specified in the installation instructions for RHEL but that seems to perform worse or the same.

**Comment by karianna** [comment]
@zwilliam12 Oracle Linux is not officially supported (https://adoptium.net/en-GB/supported-platforms).  What version of RHEL did you attempt this on?

**Comment by gdams** [comment]
@zwilliam12 I'm not sure what you're trying to install? Assuming it's temurin the naming schema is this:

```
dnf install temurin-<version>-jdk
```

e.g

```
dnf install temurin-17-jdk
```

**Comment by gdams** [comment]
I'm going to close this issue. Please reopen it if I haven't solved your issue.
