### ISSUE TITLE
Missing Debian packages for latest 382 build of temurin-8-jdk

### ISSUE THREAD

**Issue by bascht** [adoptium/installer#756]
We're probably running into a similar issue as https://github.com/adoptium/installer/issues/754:
 
![Screenshot-2023-10-24-090210](https://github.com/adoptium/installer/assets/51264/3091fcaf-8c65-48db-818c-0af4a955d79a)

I could install 8.0.372.0.0+7-1 just fine, but it seems like 8.0.382 is not yet staged / missing from the CDN?

**Comment by karianna** [comment]
@bascht Can you update your ca-certifcates package and try again?

**Comment by bascht** [comment]
@karianna Thanks for your reply. I don't think it was related to a missing or outdated CA. Got the same error message when I tried to open the .deb URL in any browser. (I also saw intermittent 50x errors from jfrog yesterday). 

Just retested with 8.0.352 and now everything is back to normal, so I guess this must've been a temporary fluke.
