### ISSUE TITLE
jenkins apline and debian build failures when using arch=all for arch != x86_64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/installer#764]
adoptium jenkins apline and debian build failures when using arch=all for arch != x86_64. The error message is like

```
+ ./gradlew packageJdkDebian --parallel -PPRODUCT=temurin -PPRODUCT_VERSION= -PARCH=armhf
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jenkins/workspace/adoptium-packages-linux-pipeline_new/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':jdk:alpine'.
> For input string: ""
```

**Comment by sophia-guo** [comment]
For debain , quick search shows that [VERSION](https://github.com/adoptium/installer/blob/master/linux/Jenkinsfile#L324) should be ${env.VERSION}. But not sure why it works for x86_64.

**Comment by sophia-guo** [comment]
Interesting about parameter VERSION. For example
VERSION is right for https://github.com/adoptium/installer/blob/master/linux/Jenkinsfile#L280
but then invisible to https://github.com/adoptium/installer/blob/master/linux/Jenkinsfile#L285

https://github.com/adoptium/installer/blob/master/linux/Jenkinsfile#L280-L285https://ci.adoptium.net/job/Grinder/7935/

**Comment by sophia-guo** [comment]
Build per arch won't have this problem.

**Comment by sophia-guo** [comment]
Might be the reason of https://github.com/adoptium/installer/issues/766

**Comment by karianna** [comment]
Hi folks, we're aware of the issue and are investigating with our CDN and package repo providers.

**Comment by gdams** [comment]
@karianna  @sophia-guo the CDN won't affect the uploads as we upload to https://adoptium.jfrog.io (directly)

**Comment by steelhead31** [comment]
The installers process works great when running for a single Arch/Dist combo, I'm currently looking at ways to improve the process to work with the parallel options.

**Comment by sophia-guo** [comment]
@gdams I think this issue is the reason why there was extra folder temurin-$(VERSION) created during the release process https://adoptium.slack.com/archives/CLCFNV2JG/p1698408183742899
