### ISSUE TITLE
HTTP 501 when downloading files from Artifactory

### ISSUE THREAD

**Issue by shollander** [adoptium/installer#765]
I can't download RPM files from https://packages.adoptium.net/artifactory/rpm

For example: GET https://packages.adoptium.net/artifactory/rpm/rocky/8/x86_64/Packages/temurin-21-jdk-21.0.1.0.0.12-1.x86_64.rpm
results in HTTP 501.

**Comment by karianna** [comment]
Hi folks, we're aware of the issue and are investigating with our CDN and package repo providers.

**Comment by steelhead31** [comment]
@shollander I believe this is now working correctly, would you mind checking if its working for you?

**Comment by shollander** [comment]
@steelhead31 Yes, it is working for me now.
Thanks for your help!
