### ISSUE TITLE
CentOS/RHEL/Fedora repo is not working 

### ISSUE THREAD

**Issue by pandeyv-del** [adoptium/installer#813]
Adding on the issue:

Looks like yes there is some issue while accessing the repo. i was adding the repo in packer to build new AMI with jdk21 but getting the below error:

`https://packages.adoptium.net/artifactory/rpm/centos//repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
    amazon-ebs: Trying other mirror.
    amazon-ebs: To address this issue please refer to the below wiki article
    amazon-ebs:
    amazon-ebs: https://wiki.centos.org/yum-errors
    amazon-ebs:
    amazon-ebs: If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
    amazon-ebs:
    amazon-ebs:
    amazon-ebs:
    amazon-ebs:  One of the configured repositories failed (Adoptium),
    amazon-ebs:  and yum doesn't have enough cached data to continue. At this point the only
    amazon-ebs:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    amazon-ebs:
    amazon-ebs:      1. Contact the upstream for the repository and get them to fix the problem.
    amazon-ebs:
    amazon-ebs:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    amazon-ebs:         upstream. This is most often useful if you are using a newer
    amazon-ebs:         distribution release than is supported by the repository (and the
    amazon-ebs:         packages for the previous distribution release still work).
    amazon-ebs:
    amazon-ebs:      3. Run the command with the repository temporarily disabled
    amazon-ebs:             yum --disablerepo=Adoptium ...
    amazon-ebs:
    amazon-ebs:      4. Disable the repository permanently, so yum won't use it by default. Yum
    amazon-ebs:         will then just ignore the repository until you permanently enable it
    amazon-ebs:         again or use --enablerepo for temporary usage:
    amazon-ebs:
    amazon-ebs:             yum-config-manager --disable Adoptium
    amazon-ebs:         or
    amazon-ebs:             subscription-manager repos --disable=Adoptium
    amazon-ebs:
    amazon-ebs:      5. Configure the failing repository to be skipped, if it is unavailable.
    amazon-ebs:         Note that yum will try to contact the repo. when it runs most commands,
    amazon-ebs:         so will have to try and fail each time (and thus. yum will be be much
    amazon-ebs:         slower). If it is a very temporary problem though, this is often a nice
    amazon-ebs:         compromise:
    amazon-ebs:
    amazon-ebs:             yum-config-manager --save --setopt=Adoptium.skip_if_unavailable=true
    amazon-ebs:
    amazon-ebs: failure: repodata/repomd.xml from Adoptium: [Errno 256] No more mirrors to try.
    amazon-ebs: https://packages.adoptium.net/artifactory/rpm/centos//repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...`

I tried both VPN and and without VPN and on different machine also. when you try to open URL https://packages.adoptium.net/artifactory/rpm/centos//repodata/repomd.xml for a moment it will show then throws error.

![image](https://github.com/adoptium/installer/assets/87751031/7c0bc6b4-1c3c-4cd5-bdd6-8269ccc8479c)

Please let us know on this if some issue is going on.

Thanks
Vinod

**Comment by karianna** [comment]
See https://github.com/adoptium/adoptium-support/issues/1006
