### ISSUE TITLE
Support for new distributions - April 2024

### ISSUE THREAD

**Issue by sxa** [adoptium/installer#852]
I mentioned this to @steelhead31 earlier as i hit an issue with this earlier today. There are some more distributions that we should look at adding to the ones that "just work" in the JFrog repos:
- Debian `trixie`
- Ubuntu 24.04 LTS `noble`
- Fedora 40
If we can get these operational for the April PSU updates I think that would be very useful.

**Comment by sxa** [comment]
Reopening this because `adoptium-ca-certificates` is not available when attempting to install on trixie/noble - I expect it needs some redirects added to those paths on the JFrog artifactory instance:
```
oot@9d8ee135c1cb:/# apt install temurin-17-jre
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 temurin-17-jre : Depends: adoptium-ca-certificates but it is not installable
                  Recommends: fonts-dejavu-extra but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@9d8ee135c1cb:/# 
```

**Comment by steelhead31** [comment]
Additional work is needed to update the CA-CERTIFICATES if adding debian/ubuntu distributions..

This PR has details, https://github.com/adoptium/installer/pull/868

**Comment by steelhead31** [comment]
Bug raised with jf-cli upstream as error encountered when trying to upload ca certs for multiple distros..

https://github.com/jfrog/jfrog-cli/issues/2532

**Comment by steelhead31** [comment]
The above PR has now been merged with appropriate fixes for the cli . Tested installation of JDK/JRE11,17 & 21 on both Noble & Trixie successfully.
