### ISSUE TITLE
Generated MSIs lack end-user license agreement

### ISSUE THREAD

**Issue by jmjaffe37** [adoptium/installer#888]
Not sure if this was a desired change, but we recently noticed that the generated MSIs (windows installers) will no-longer show the End-User License Agreement page (see example below of what the page looks like). I looked for a while, but I could not find the code change that lead to this

![image](https://github.com/adoptium/installer/assets/111303274/4f0af90a-5529-4231-b3ec-9263803a19f4)

**Comment by gdams** [comment]
@jmjaffe37 I noticed this when testing, it looks like we need to add this back as part of the flow.

**Comment by jmjaffe37** [comment]
Looks like this was originally addressed as a feature request here https://github.com/adoptium/installer/issues/162

**Comment by karianna** [comment]
I guess we need to provide an override capability.

**Comment by jmjaffe37** [comment]
> I guess we need to provide an override capability.

The override capability was already implemented by @douph1. It depends on the JVM:
- For Openj9, the `license-OpenJ9.en-us.rtf` license is shown
- For hotspot, the `license-GPLv2+CE.en-us.rtf` is used (and skipped since it is optional)
- Otherwise it says that there is no license defined for other custom JVMs

**Comment by jmjaffe37** [comment]
I should be able to add in the capability for the user specify that they want to show the optional GPL license. Would that be prefereable?

**Comment by karianna** [comment]
I think we need to alter it so it's not vm based but "vm and vendor" based.  I know that other non Adoptium vendors also have EULA's (on a hotspot base).

**Comment by jmjaffe37** [comment]
> I think we need to alter it so it's not vm based but "vm and vendor" based. I know that other non Adoptium vendors also have EULA's (on a hotspot base).

Ok, that can be arranged

**Comment by jmjaffe37** [comment]
> I think we need to alter it so it's not vm based but "vm and vendor" based. I know that other non Adoptium vendors also have EULA's (on a hotspot base).

Feature added in https://github.com/adoptium/installer/pull/851. Also added sample code and an explanation of how to implement custom end-user license behavior in the readme

**Comment by jmjaffe37** [comment]
The vendor_based license logic has been removed (as was decided recently), but the README now has documentation on license behavior. If similar logic is desired in the future, it will be quick and easy to implement

**Comment by karianna** [comment]
Thank you!
