### ISSUE TITLE
Alpine temurin ARM64 Package depends on x86 Package

### ISSUE THREAD

**Issue by vector-kainzbauer** [adoptium/installer#892]
Since a few days (5-12 days) we can't install temurin-21 ARM64 Packages, when we use the alpine:3.19 docker image as environment. 
The error happens using buildx, but also using RancherDesktop on a ARM64 mac.

We run the command:
`wget -O /etc/apk/keys/adoptium.rsa.pub https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk &&     echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >> /etc/apk/repositories &&     apk add -q --update --no-cache temurin-21-jdk`
And get the error: 
```
ERROR: unable to select packages:
   so:libc.musl-x86_64.so.1 (no such package):
   required by: temurin-21-jdk-21.0.3_p9-r0[so:libc.musl-x86_64.so.1]
```
Can you help us with this problem? 
Thanks in advance!

**Comment by cmahnke** [comment]
This also applies to `temurin-22-jdk`, `temurin-22-jre` and `temurin-21-jre` and seems to be systematic problem.

**Comment by sxa** [comment]
Looks like https://packages.adoptium.net/artifactory/apk/alpine/main/aarch64/APKINDEX.tar.gz has:
```
D:java-common java-cacerts so:libasound.so.2 so:libc.musl-x86_64.so.1
```
which is the likely cause of this

**Comment by vector-kainzbauer** [comment]
@sxa Thanks a lot for the quick fix!
Could you please let me know when the fixed version will be released on your Artifactory?"

**Comment by steelhead31** [comment]
Re-opened, to track the additional package push, currently investigating this.

**Comment by steelhead31** [comment]
I've tested local builds of JDK21 on Alpine 3.19 docker containers.. here are the results, I'll only be able to test the download from artifactory, once the packages are uploaded, but they do appear to work ok.  
 

Arm64  
`3dd97d6feeff:~# apk add ./temurin-21-jdk-21.0.3_p9-r1.apk`  
`(1/4) Installing java-common (0.5-r0)`  
`(2/4) Installing p11-kit-trust (0.25.3-r0)`  
`(3/4) Installing java-cacerts (1.0-r1)`  
`(4/4) Installing temurin-21-jdk (21.0.3_p9-r1)`  
`Executing busybox-1.36.1-r15.trigger`  
`Executing ca-certificates-20230506-r0.trigger`  
`Executing java-common-0.5-r0.trigger`  
`OK: 590 MiB in 170 packages`  
`3dd97d6feeff:~# java -version`  
`openjdk version "21.0.3" 2024-04-16 LTS`  
`OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)`  
`OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)`  
  
X64  
`apk add ./temurin-21-jdk-21.0.3_p9-r1.apk`  
`fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz`  
`fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz`  
`(1/4) Installing java-common (0.5-r0)`  
`(2/4) Installing p11-kit-trust (0.25.3-r0)`  
`(3/4) Installing java-cacerts (1.0-r1)`  
`(4/4) Installing temurin-21-jdk (21.0.3_p9-r1)`  
`Executing busybox-1.36.1-r15.trigger`  
`Executing ca-certificates-20240226-r0.trigger`  
`Executing java-common-0.5-r0.trigger`  
`OK: 586 MiB in 170 packages`  
`f2c26aea4afa:/# java -version`  
`openjdk version "21.0.3" 2024-04-16 LTS`  
`OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)`  
`OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)`

**Comment by sxa** [comment]
> I'll only be able to test the download from artifactory, once the packages are uploaded, but they do appear to work ok.

Given that the current package is fundamentally useless and won't install I'm personally ok with trying to push up the new `r1` version and see how it works ;-)

**Comment by steelhead31** [comment]
JDK22 Tests..  
  
x64

  
`f2c26aea4afa:/# apk add ./temurin-22-jdk-22.0.1_p8-r1.apk`  
`(1/1) Installing temurin-22-jdk (22.0.1_p8-r1)`  
`Executing java-common-0.5-r0.trigger`  
`OK: 870 MiB in 171 packages`  
`f2c26aea4afa:/# java -version`  
`openjdk version "22.0.1" 2024-04-16`  
`OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)`  
`OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)`

Arm64

`apk add ./temurin-22-jdk-22.0.1_p8-r1.apk --allow-untrusted`  
`fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz`  
`fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz`  
`(1/4) Installing java-common (0.5-r0)`  
`(2/4) Installing p11-kit-trust (0.25.3-r0)`  
`(3/4) Installing java-cacerts (1.0-r1)`  
`(4/4) Installing temurin-22-jdk (22.0.1_p8-r1)`  
`Executing busybox-1.36.1-r15.trigger`  
`Executing ca-certificates-20230506-r0.trigger`  
`Executing java-common-0.5-r0.trigger`  
`OK: 586 MiB in 170 packages`  
`1d1867c83a46:/# java -version`  
`openjdk version "22.0.1" 2024-04-16`  
`OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)`  
`OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)`

**Comment by steelhead31** [comment]
@vector-kainzbauer  all of the x64/aarch64 JDK/JRE21 & JDK/JRE22 Alpine packages have been uploaded to artifactory, I've done a few tests, and they all appear to be ok now. Please let me know if you have any issues.

**Comment by vector-kainzbauer** [comment]
Works like expected again, thanks for the quick help!
