### ISSUE TITLE
No release for Ubuntu mantic

### ISSUE THREAD

**Issue by leventyalcin** [adoptium/installer#922]
Hi, 

I am on Ubuntu 23.10 mantic. When I followed the [installation steps](https://adoptium.net/en-GB/installation/linux/#_deb_installation_on_debian_or_ubuntu), I am seeing the following error with `apt update`. 

```bash
 E: The repository 'https://packages.adoptium.net/artifactory/deb mantic Release' does not have a Release file.
```

When I checked the repository, I couldn't see any release for `mantic`. However Ubuntu 24.04 noble seems to be there for example.

```bash
curl -s https://packages.adoptium.net/artifactory/deb/dists|grep -i mantic; echo $?
1
curl -s https://packages.adoptium.net/artifactory/deb/dists|grep -i noble && echo $?
<a href="noble/">noble/</a>     14-May-2024 14:26    -
0
```
I wonder if I am missing anything or there is a particular reason for it. 

Thanks,

**Comment by sxa** [comment]
We don't always add the STS versions in, although since the packages are identical across all versions, feel free to just switch `mantic` for `noble` or any of the other ones as a workaround if you still need to use 23.10.

**Comment by sxa** [comment]
Closing on the basis that
- Mantic (23.10) is now out of support
- We don't currently have other STS versions included explicitly in the installer repositories
- There is an easy workaround
