### ISSUE TITLE
JRE RPM package is not signed

### ISSUE THREAD

**Issue by bebanowski** [adoptium/installer#962]
Same situation as https://github.com/adoptium/installer/issues/611, only for a newer release 

Package temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm is not signed

Signature is missing here:
```
$ rpm -qpi temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm
Name        : temurin-17-jre
Version     : 17.0.12.0.0.7
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : java
Size        : 140814170
License     : GPLv2 with exceptions
Signature   : (none)
Source RPM  : temurin-17-jre-17.0.12.0.0.7-1.src.rpm
Build Date  : Wed 24 Jul 2024 10:57:12 BST
Build Host  : c795d3e09c70
Relocations : /usr/lib/jvm/temurin-17-jre
Packager    : Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org>
Vendor      : Eclipse Adoptium
URL         : https://projects.eclipse.org/projects/adoptium
Summary     : Eclipse Temurin 17 JRE
Description :
Eclipse Temurin JRE is an OpenJDK-based runtime environment to execute
applications and components using the programming language Java.
```

Can this be signed so we don't have to bypass the GPG check?

**Comment by karianna** [comment]
@jerboaa Are you able to confirm?

**Comment by steelhead31** [comment]
@bebanowski & @waeller 

Would you mind re-downloading the file and trying again.. there was a slight issue when the files were being uploaded last evening..

This has subsequently been rectified, but I believe you may have caught the invalid version of the package..

```
cfryer@scfryer-thinkpadp1gen2:~/Downloads$ rpm -qpi temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm
Name        : temurin-17-jre
Version     : 17.0.12.0.0.7
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : java
Size        : 140809828
License     : GPLv2 with exceptions
Signature   : RSA/SHA256, Wed 24 Jul 2024 01:50:54 PM BST, Key ID 843c48a565f8f04b
Source RPM  : temurin-17-jre-17.0.12.0.0.7-1.src.rpm
Build Date  : Wed 24 Jul 2024 01:45:56 PM BST
Build Host  : c62056947c1d
Relocations : /usr/lib64/jvm/temurin-17-jre 
Packager    : Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org>
Vendor      : Eclipse Adoptium
URL         : https://projects.eclipse.org/projects/adoptium
Summary     : Eclipse Temurin 17 JRE
Description :
Eclipse Temurin JRE is an OpenJDK-based runtime environment to execute
applications and components using the programming language Java.
```

**Comment by waeller** [comment]
Nope, still the same error:

```
> sudo yum clean all; sudo yum update temurin-17-jre
...
Downloading packages:

Package temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm is not signed  48% [==========================                            ]  0.0 B/s |  13 MB  --:--:-- ETA 
temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm                                                                                              |  26 MB  00:00:01     

Package temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm is not signed

> rpm -qpi /var/cache/yum/x86_64/7/adoptium/packages/temurin-17-jre-17.0.12.0.0.7-1.x86_64.rpm 
Name        : temurin-17-jre
Version     : 17.0.12.0.0.7
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : java
Size        : 140814170
License     : GPLv2 with exceptions
Signature   : (none)
Source RPM  : temurin-17-jre-17.0.12.0.0.7-1.src.rpm
Build Date  : Wed 24 Jul 2024 11:57:12 AM CEST
Build Host  : c795d3e09c70
Relocations : /usr/lib/jvm/temurin-17-jre 
Packager    : Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org>
Vendor      : Eclipse Adoptium
URL         : https://projects.eclipse.org/projects/adoptium
Summary     : Eclipse Temurin 17 JRE
Description :
Eclipse Temurin JRE is an OpenJDK-based runtime environment to execute
applications and components using the programming language Java.
```

Maybe the wrong version is still on some mirror(s)?

**Comment by steelhead31** [comment]
Possibly, which O/S are you downloading on, I'll try and replicate it..

**Comment by waeller** [comment]
It's a Centos 7 (yeah, I know ... we are working on it ;-)

**Comment by steelhead31** [comment]
Im going to push an updated spec version 2 to the repository, so pulling the latest should get that... shouldn't take long, but I'll update here when its done.

**Comment by bebanowski** [comment]
Still affecting me on AlmaLinux 9, will wait for your update.

**Comment by steelhead31** [comment]
JRE packages with spec version 2 are now uploaded..

  
`rpm -qpi temurin-17-jre-17.0.12.0.0.7-2.x86_64.rpm`  
`Name        : temurin-17-jre`  
`Version     : 17.0.12.0.0.7`  
`Release     : 2`  
`Architecture: x86_64`  
`Install Date: (not installed)`  
`Group       : java`  
`Size        : 140814170`  
`License     : GPLv2 with exceptions`  
`Signature   : RSA/SHA256, Thu 25 Jul 2024 02:42:05 PM BST, Key ID 843c48a565f8f04b`  
`Source RPM  : temurin-17-jre-17.0.12.0.0.7-2.src.rpm`  
`Build Date  : Thu 25 Jul 2024 02:35:47 PM BST`  
`Build Host  : e281dedea046`  
`Relocations : /usr/lib/jvm/temurin-17-jre`   
`Packager    : Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org>`  
`Vendor      : Eclipse Adoptium`  
`URL         : https://projects.eclipse.org/projects/adoptium`  
`Summary     : Eclipse Temurin 17 JRE`  
`Description :`  
`Eclipse Temurin JRE is an OpenJDK-based runtime environment to execute`  
 

JDK packages are still in progress...

**Comment by waeller** [comment]
Can confirm: temurin-17-jre is fine :)

Thanks!

**Comment by steelhead31** [comment]
Temurin 17 JDKs (spec2) have now been uploaded..  
  
`rpm -qpi temurin-17-jdk-17.0.12.0.0.7-2.x86_64.rpm`  
`Name        : temurin-17-jdk`  
`Version     : 17.0.12.0.0.7`  
`Release     : 2`  
`Architecture: x86_64`  
`Install Date: (not installed)`  
`Group       : java`  
`Size        : 330688629`  
`License     : GPLv2 with exceptions`  
`Signature   : RSA/SHA256, Thu 25 Jul 2024 03:27:05 PM BST, Key ID 843c48a565f8f04b`  
`Source RPM  : temurin-17-jdk-17.0.12.0.0.7-2.src.rpm`  
`Build Date  : Thu 25 Jul 2024 03:12:33 PM BST`  
`Build Host  : 78f47f47c015`  
`Relocations : /usr/lib/jvm/temurin-17-jdk`   
`Packager    : Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org>`  
`Vendor      : Eclipse Adoptium`  
`URL         : https://projects.eclipse.org/projects/adoptium`  
`Summary     : Eclipse Temurin 17 JDK`  
`Description :`  
`Eclipse Temurin JDK is an OpenJDK-based development environment to create`  
`applications and components using the programming language Java.`

**Comment by steelhead31** [comment]
Please re-open / let me know if you have any more issues.
